
var Vips = (() => {
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var n=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="function"==typeof importScripts,u="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,w=ea&&"em-pthread"==self.name;if(u){var fa=require("worker_threads");global.Worker=fa.Worker;w=(ea=!fa.cf)&&"em-pthread"==fa.workerData}var ha=Object.assign({},n),ia="./this.program",ja=(a,b)=>{throw b;},ka;
"undefined"!==typeof __filename?ka=__filename:ea?ka=self.location.href:ka=void 0;var la="",ma,na,oa;
if(u){var fs=require("fs"),x=require("path");la=__dirname+"/";ma=(a,b)=>{a=pa(a)?new URL(a):x.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};oa=a=>{a=ma(a,!0);a.buffer||(a=new Uint8Array(a));return a};na=(a,b,c)=>{a=pa(a)?new URL(a):x.normalize(a);fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})};!n.thisProgram&&1<process.argv.length&&(ia=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);ja=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea)ka.startsWith("blob:")||(la=ka.substr(0,
ka.replace(/[?#].*/,"").lastIndexOf("/")+1)),u||(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ea&&(oa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),na=(a,b,c)=>{fetch(a,{credentials:"same-origin"}).then(d=>d.ok?d.arrayBuffer():Promise.reject(Error(d.status+" : "+d.url))).then(b,c)});u&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);
var qa=console.log.bind(console),ra=console.error.bind(console);u&&(qa=(...a)=>fs.writeSync(1,a.join(" ")+"\n"),ra=(...a)=>fs.writeSync(2,a.join(" ")+"\n"));var sa=n.print||qa,y=n.printErr||ra;Object.assign(n,ha);ha=null;n.thisProgram&&(ia=n.thisProgram);n.quit&&(ja=n.quit);
if(w){var ta;if(u){var ua=fa.parentPort;ua.on("message",c=>onmessage({data:c}));Object.assign(globalThis,{self:global,importScripts:()=>{},postMessage:c=>ua.postMessage(c),performance:global.performance||{now:Date.now}})}var va=!1;function a(...c){c=c.join(" ");u?fs.writeSync(2,c+"\n"):console.error(c)}n.printErr||(y=a);self.alert=function(...c){postMessage({Md:"alert",text:c.join(" "),gf:wa()})};n.instantiateWasm=(c,d)=>new Promise(e=>{ta=f=>{f=new WebAssembly.Instance(f,xa());d(f);e()}});self.onunhandledrejection=
c=>{throw c.reason||c;};function b(c){try{var d=c.data,e=d.cmd;if("load"===e){let f=[];self.onmessage=g=>f.push(g);self.startWorker=()=>{postMessage({cmd:"loaded"});for(let g of f)b(g);self.onmessage=b};for(const g of d.handlers)if(!n[g]||n[g].proxy)n[g]=(...h)=>{postMessage({Md:"callHandler",bf:g,args:h})},"print"==g&&(sa=n[g]),"printErr"==g&&(y=n[g]);ya=d.wasmMemory;za();ta(d.wasmModule)}else if("run"===e){Aa(d.pthread_ptr,0,0,1,0,0);Ba(d.pthread_ptr);Ca();Da();va||(Ea(),va=!0);try{Fa(d.start_routine,
d.arg)}catch(f){if("unwind"!=f)throw f;}}else"cancel"===e?wa()&&Ga(-1):"setimmediate"!==d.target&&("checkMailbox"===e?va&&Ha():e&&(y(`worker: received unknown command ${e}`),y(d)))}catch(f){throw Ia(),f;}}self.onmessage=b}var Ja;n.wasmBinary&&(Ja=n.wasmBinary);var ya,Ka,La=!1,Ma,z,A,Na,B,C,D,Oa,E,Pa,Qa;
function za(){var a=ya.buffer;n.HEAP8=z=new Int8Array(a);n.HEAP16=Na=new Int16Array(a);n.HEAPU8=A=new Uint8Array(a);n.HEAPU16=B=new Uint16Array(a);n.HEAP32=C=new Int32Array(a);n.HEAPU32=D=new Uint32Array(a);n.HEAPF32=Oa=new Float32Array(a);n.HEAPF64=Qa=new Float64Array(a);n.HEAP64=E=new BigInt64Array(a);n.HEAPU64=Pa=new BigUint64Array(a)}
if(!w){if(n.wasmMemory)ya=n.wasmMemory;else{var Ra=n.INITIAL_MEMORY||268435456;ya=new WebAssembly.Memory({initial:Ra/65536,maximum:Ra/65536,shared:!0});if(!(ya.buffer instanceof SharedArrayBuffer))throw y("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),u&&y("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");}za()}var Sa=[],Ta=[],Ua=[],Va=[],Wa=[],Ya=!1;function Za(){w||(n.noFSInit||FS.init.zd||FS.init(),FS.Ud=!1,$a(Ta))}var ab=0,bb=null,cb=null;function db(){ab++;n.monitorRunDependencies?.(ab)}function eb(){ab--;n.monitorRunDependencies?.(ab);if(0==ab&&(null!==bb&&(clearInterval(bb),bb=null),cb)){var a=cb;cb=null;a()}}function fb(a){n.onAbort?.(a);a="Aborted("+a+")";y(a);La=!0;Ma=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}
var gb=a=>a.startsWith("data:application/octet-stream;base64,"),pa=a=>a.startsWith("file://");class F extends Error{}class hb extends F{}class ib extends F{constructor(a){super(a);this.Uc=a;a=jb(a);this.name=a[0];this.message=a[1]}}var kb;function lb(a){if(a==kb&&Ja)return new Uint8Array(Ja);if(oa)return oa(a);throw"both async and sync fetching of the wasm failed";}
function mb(a){return Ja?Promise.resolve().then(()=>lb(a)):new Promise((b,c)=>{na(a,d=>b(new Uint8Array(d)),()=>{try{b(lb(a))}catch(d){c(d)}})})}function nb(a,b,c){return mb(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{y(`failed to asynchronously prepare wasm: ${d}`);fb(d)})}
function ob(a,b){var c=kb;return Ja||"function"!=typeof WebAssembly.instantiateStreaming||gb(c)||u||"function"!=typeof fetch?nb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){y(`wasm streaming compile failed: ${e}`);y("falling back to ArrayBuffer instantiation");return nb(c,a,b)}))}
function xa(){pb={m:qb,eb:rb,Ya:sb,b:tb,h:ub,P:vb,gb:wb,e:xb,Aa:yb,Ba:zb,ba:Ab,wb:Bb,sb:Cb,rb:Db,Ea:Eb,tb:Fb,ub:Gb,U:Hb,ib:Ib,db:Jb,vb:Kb,xa:Lb,Ca:Mb,Qa:Nb,qa:Ob,ga:Pb,Ma:Qb,z:Rb,j:Sb,B:Tb,f:Ub,v:Vb,La:Wb,r:Xb,i:Yb,fa:Zb,F:$b,E:ac,w:bc,ea:cc,X:dc,ra:ec,Ra:fc,Na:gc,yb:hc,pb:ic,bb:jc,hb:kc,fb:lc,ya:mc,ob:Ba,xb:nc,Za:oc,D:pc,H:qc,zb:rc,y:sc,I:tc,Q:uc,Wa:vc,$:wc,Va:xc,ta:yc,Ua:zc,K:Ac,Xa:Bc,Sa:Cc,x:Dc,ua:Ec,lb:Fc,mb:Gc,jb:Hc,kb:Ic,ab:Jc,za:Kc,wa:Lc,R:Mc,sa:Nc,cb:Oc,C:Pc,ca:Qc,$a:Rc,Fa:Sc,Ga:Tc,W:Uc,O:Vc,
qb:Wc,aa:Xc,nb:Yc,V:Zc,Ha:$c,_a:ad,_:bd,u:cd,Ta:dd,s:ed,d:fd,k:gd,t:hd,g:jd,va:kd,q:ld,A:md,Ka:nd,Ja:od,da:pd,N:qd,c:rd,oa:sd,o:td,T:ud,J:vd,ha:wd,S:xd,l:yd,pa:zd,ma:Ad,la:Bd,na:Cd,ja:Dd,ka:Ed,p:Fd,n:Gd,G:Hd,L:Id,Oa:Jd,ia:Kd,M:Ld,Pa:Md,Z:Nd,Y:Od,a:ya,Da:Pd,Ia:Qd};return{a:pb}}function Rd(a){for(var b=B[a+6>>1];13===b&&!(16<D[a>>2]);){var c=D[a+8>>2],d=D[c>>2];if(0===d){b=0;break}else if(0===D[(c>>2)+1])a=d,b=B[d+6>>1];else break}return[a,b]}
function $c(a,b,c,d){var e=D[(a>>2)+1],f=D[(a>>2)+6],g=D[(a>>2)+2];a=Rd(D[(a>>2)+3])[1];var h=H(),k=h,m=[],p=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)m.push(c),p=!0;for(var q=0;q<f;q++){var r=D[(d>>2)+q],l=Rd(D[(g>>2)+q]),t=l[0];l=l[1];switch(l){case 1:case 10:case 9:case 14:m.push(D[r>>2]);break;case 2:m.push(Oa[r>>2]);break;case 3:m.push(Qa[r>>3]);break;case 5:m.push(A[r]);break;case 6:m.push(z[r]);break;case 7:m.push(B[r>>
1]);break;case 8:m.push(Na[r>>1]);break;case 11:case 12:m.push(Pa[r>>3]);break;case 4:m.push(Pa[r>>3]);m.push(Pa[(r>>3)+1]);break;case 13:l=D[t>>2];t=B[t+4>>1];k-=l;k&=~(t-1);z.subarray(k,k+l).set(z.subarray(r,r+l));m.push(k);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+l);}}if(f!=e){var v=[];for(q=e-1;q>=f;q--)switch(r=D[(d>>2)+q],l=Rd(D[(g>>2)+q]),t=l[0],l=l[1],l){case 5:case 6:--k;k&=-1;A[k]=A[r];break;case 7:case 8:k-=2;k&=-2;B[k>>1]=B[r>>1];break;
case 1:case 9:case 10:case 14:case 2:k-=4;k&=-4;D[k>>2]=D[r>>2];break;case 3:case 11:case 12:k-=8;k&=-8;D[k>>2]=D[r>>2];D[(k>>2)+1]=D[(r>>2)+1];break;case 4:k-=16;k&=-8;D[k>>2]=D[r>>2];D[(k>>2)+1]=D[(r>>2)+1];D[(k>>2)+2]=D[(r>>2)+2];D[(k>>2)+3]=D[(r>>2)+3];break;case 13:k-=4;k&=-4;v.push([k,r,D[t>>2],B[t+4>>1]]);break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+l);}m.push(k);for(q=0;q<v.length;q++)e=v[q],d=e[0],r=e[1],l=e[2],t=e[3],k-=l,k&=~(t-1),z.subarray(k,
k+l).set(z.subarray(r,r+l)),D[d>>2]=k}I(k);Sd(0);b=J.get(b).apply(null,m);I(h);if(!p)switch(a){case 0:break;case 1:case 9:case 10:case 14:D[c>>2]=b;break;case 2:Oa[c>>2]=b;break;case 3:Qa[c>>3]=b;break;case 5:case 6:A[c+0]=b;break;case 7:case 8:B[c>>1]=b;break;case 11:case 12:Pa[c>>3]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}function Td(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ud=a=>{a.terminate();a.onmessage=()=>{}},Zd=a=>{if(0==Vd.length){var b=ka;n.mainScriptUrlOrBlob&&(b=n.mainScriptUrlOrBlob,"string"!=typeof b&&(b=URL.createObjectURL(b)));b=new Worker(b,{workerData:"em-pthread",name:"em-pthread"});Vd.push(b);Wd()}b=Vd.pop();if(!b)return 6;Xd.push(b);Yd[a.ad]=b;b.ad=a.ad;var c={cmd:"run",start_routine:a.Le,arg:a.ee,pthread_ptr:a.ad};u&&b.unref();b.postMessage(c,a.Qe);return 0},$d=0,ae=a=>-9007199254740992>a||9007199254740992<a?NaN:Number(a),L=(a,b,...c)=>{for(var d=
2*c.length,e=H(),f=Sd(8*d),g=f>>3,h=0;h<c.length;h++){var k=c[h];"bigint"==typeof k?(E[g+2*h]=1n,E[g+2*h+1]=k):(E[g+2*h]=0n,Qa[g+2*h+1]=k)}a=be(a,0,d,f,b);I(e);return a};function Pd(a){if(w)return L(0,1,a);Ma=a;ce||0<$d||(de(),n.onExit?.(a),La=!0);ja(a,new Td(a))}var ee=a=>{a instanceof Td||"unwind"==a||ja(1,a)};function fe(a){if(w)return L(1,0,a);Uc(a)}
var Uc=a=>{Ma=a;if(w)throw fe(a),"unwind";if(!(ce||0<$d||w)){ge();$a(Va);FS.init.zd=!1;he(0);for(var b=0;b<FS.streams.length;b++){var c=FS.streams[b];c&&FS.close(c)}de();Ya=!0}Pd(a)},Vd=[],Xd=[],ie=[],Yd={},de=()=>{for(var a of Xd)Ud(a);for(a of Vd)Ud(a);Vd=[];Xd=[];Yd=[]},ke=a=>{var b=a.ad;delete Yd[b];Vd.push(a);Xd.splice(Xd.indexOf(a),1);a.ad=0;je(b)};function Da(){ie.forEach(a=>a())}
var Wd=()=>{var a=Vd[0];new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.cmd;if(f.targetThread&&f.targetThread!=wa()){var h=Yd[f.targetThread];h?h.postMessage(f,f.transferList):y(`Internal error! Worker sent a message "${g}" to target pthread ${f.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ha();else if("spawnThread"===g)Zd(f);else if("cleanupThread"===g)ke(Yd[f.thread]);else if("killThread"===g)f=f.thread,g=Yd[f],delete Yd[f],Ud(g),je(f),Xd.splice(Xd.indexOf(g),1),
g.ad=0;else if("cancelThread"===g)Yd[f.thread].postMessage({cmd:"cancel"});else if("loaded"===g)a.loaded=!0,b(a);else if("alert"===g)alert(`Thread ${f.threadId}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)n[f.handler](...f.args);else g&&y(`worker sent an unknown command ${g}`)};a.onerror=f=>{y(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};u&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=
[],d=["onExit","onAbort","print","printErr"],e;for(e of d)n.propertyIsEnumerable(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,wasmMemory:ya,wasmModule:Ka})})},$a=a=>{for(;0<a.length;)a.shift()(n)},Ca=()=>{var a=wa(),b=D[a+52>>2];le(b,b-D[a+56>>2]);I(b)},J,Fa=(a,b)=>{$d=0;a=J.get(a)(b);ce||0<$d?Ma=a:Ga(a)},ce=n.noExitRuntime||!1,me=new TextDecoder("utf8"),M=(a,b)=>{if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&A[c];)++c;return me.decode(A.slice(a,c))},qb=(a,b,c,d)=>{fb(`Assertion failed: ${M(a)}, at: `+
[b?M(b):"unknown filename",c,d?M(d):"unknown function"])},rb=(a,b)=>J.get(a)(b),ne=[],oe=0,sb=a=>{a=new pe(a);0==z[a.yc+12]&&(z[a.yc+12]=1,oe--);z[a.yc+13]=0;ne.push(a);qe(a.Uc);if(re(D[a.yc+4>>2]))a=D[a.Uc>>2];else{var b=D[a.yc+16>>2];a=0!==b?b:a.Uc}return a},se=0;class pe{constructor(a){this.Uc=a;this.yc=a-24}init(a,b){D[this.yc+16>>2]=0;D[this.yc+4>>2]=a;D[this.yc+8>>2]=b}}
var xb=a=>{se||=new ib(a);throw se;},ve=a=>{var b=se?.Uc;if(!b)return te(0),0;var c=new pe(b);D[c.yc+16>>2]=b;var d=D[c.yc+4>>2];if(!d)return te(0),b;for(var e of a){if(0===e||e===d)break;if(ue(e,d,c.yc+16))return te(e),b}te(d);return b},tb=()=>ve([]),ub=a=>ve([a]),vb=(a,b,c)=>{(new pe(a)).init(b,c);se=new ib(a);oe++;throw se;};function we(a,b,c,d){return w?L(2,1,a,b,c,d):wb(a,b,c,d)}
var wb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return y("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(w&&0===e.length)return we(a,b,c,d);a={Le:c,ad:a,ee:d,Qe:e};return w?(a.Md="spawnThread",postMessage(a,e),0):Zd(a)},xe=(...a)=>x.posix.join(...a),ye=(a,b)=>x.posix.join(a,b),ze=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>(c.set(crypto.getRandomValues(new Uint8Array(c.byteLength))),c);if(u)try{var a=
require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}fb("initRandomDevice")},Ae=a=>(Ae=ze())(a),Be=(...a)=>{a.unshift(FS.cwd());return x.posix.resolve(...a)},Ce=(a,b)=>x.posix.relative(a||FS.cwd(),b||FS.cwd()),De=a=>{for(var b=0;a[b]&&!(NaN<=b);)++b;return me.decode(a.buffer?a.slice(0,b):new Uint8Array(a.slice(0,b)))},Ee=[],Fe=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&
57343>=d?(b+=4,++c):b+=3}return b},Ge=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};
function He(a,b){var c=Array(Fe(a)+1);a=Ge(a,c,0,c.length);b&&(c.length=a);return c}var Ie=[];function Je(a,b){Ie[a]={input:[],output:[],Wc:b};FS.registerDevice(a,Ke)}
var Ke={open(a){var b=Ie[a.node.rdev];if(!b)throw new FS.uc(43);a.tty=b;a.seekable=!1},close(a){a.tty.Wc.fsync(a.tty)},fsync(a){a.tty.Wc.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Wc.Td)throw new FS.uc(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Wc.Td(a.tty)}catch(h){throw new FS.uc(29);}if(void 0===g&&0===e)throw new FS.uc(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Wc.Dd)throw new FS.uc(60);try{for(var e=0;e<d;e++)a.tty.Wc.Dd(a.tty,
b[c+e])}catch(f){throw new FS.uc(29);}d&&(a.node.timestamp=Date.now());return e}},Le={Td(){a:{if(!Ee.length){var a=null;if(u){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}if(!a){a=null;break a}Ee=He(a,!0)}a=Ee.shift()}return a},Dd(a,b){null===b||10===b?(sa(De(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(sa(De(a.output)),a.output=
[])},te(){return{Xe:25856,Ze:5,We:191,Ye:35387,Ve:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ue(){return 0},ve(){return[24,80]}},Me={Dd(a,b){null===b||10===b?(y(De(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(y(De(a.output)),a.output=[])}},Oe=a=>{a=65536*Math.ceil(a/65536);var b=Ne(65536,a);b?(A.fill(0,b,b+a),a=b):a=0;return a};
function Pe(a,b){var c=a.zc?a.zc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.zc,a.zc=new Uint8Array(b),0<a.Cc&&a.zc.set(c.subarray(0,a.Cc),0))}
var N={Rc:null,mount(){return N.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(FS.isBlkdev(c)||FS.isFIFO(c))throw new FS.uc(63);N.Rc||(N.Rc={dir:{node:{Lc:N.xc.Lc,Fc:N.xc.Fc,lookup:N.xc.lookup,Mc:N.xc.Mc,rename:N.xc.rename,unlink:N.xc.unlink,rmdir:N.xc.rmdir,readdir:N.xc.readdir,symlink:N.xc.symlink},stream:{llseek:N.wc.llseek}},file:{node:{Lc:N.xc.Lc,Fc:N.xc.Fc},stream:{llseek:N.wc.llseek,read:N.wc.read,write:N.wc.write,dd:N.wc.dd,Pc:N.wc.Pc,Vc:N.wc.Vc}},link:{node:{Lc:N.xc.Lc,Fc:N.xc.Fc,readlink:N.xc.readlink},
stream:{}},Ld:{node:{Lc:N.xc.Lc,Fc:N.xc.Fc},stream:FS.ge}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.xc=N.Rc.dir.node,c.wc=N.Rc.dir.stream,c.zc={}):FS.isFile(c.mode)?(c.xc=N.Rc.file.node,c.wc=N.Rc.file.stream,c.Cc=0,c.zc=null):FS.isLink(c.mode)?(c.xc=N.Rc.link.node,c.wc=N.Rc.link.stream):FS.isChrdev(c.mode)&&(c.xc=N.Rc.Ld.node,c.wc=N.Rc.Ld.stream);c.timestamp=Date.now();a&&(a.zc[b]=c,a.timestamp=c.timestamp);return c},af(a){return a.zc?a.zc.subarray?a.zc.subarray(0,a.Cc):new Uint8Array(a.zc):
new Uint8Array(0)},xc:{Lc(a){var b={};b.dev=FS.isChrdev(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.Cc:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Yc=4096;b.blocks=Math.ceil(b.size/b.Yc);return b},Fc(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,
a.Cc!=b))if(0==b)a.zc=null,a.Cc=0;else{var c=a.zc;a.zc=new Uint8Array(b);c&&a.zc.set(c.subarray(0,Math.min(b,a.Cc)));a.Cc=b}},lookup(){throw FS.xd[44];},Mc(a,b,c,d){return N.createNode(a,b,c,d)},rename(a,b,c){if(FS.isDir(a.mode)){try{var d=Qe(b,c)}catch(f){}if(d)for(var e in d.zc)throw new FS.uc(55);}delete a.parent.zc[a.name];a.parent.timestamp=Date.now();a.name=c;b.zc[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.zc[b];a.timestamp=Date.now()},rmdir(a,b){var c=Qe(a,b),d;for(d in c.zc)throw new FS.uc(55);
delete a.zc[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.zc))b.push(c);return b},symlink(a,b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.uc(28);return a.link}},wc:{read(a,b,c,d,e){var f=a.node.zc;if(e>=a.node.Cc)return 0;a=Math.min(a.node.Cc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.zc||a.zc.subarray)){if(f)return a.zc=b.subarray(c,c+d),a.Cc=d;if(0===a.Cc&&0===e)return a.zc=b.slice(c,c+d),a.Cc=d;if(e+d<=a.Cc)return a.zc.set(b.subarray(c,c+d),e),d}Pe(a,e+d);if(a.zc.subarray&&b.subarray)a.zc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.zc[e+f]=b[c+f];a.Cc=Math.max(a.Cc,e+d);return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.Cc);if(0>b)throw new FS.uc(28);return b},dd(a,b,c){Pe(a.node,b+c);a.node.Cc=Math.max(a.node.Cc,b+c)},Pc(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.uc(43);
a=a.node.zc;if(e&2||a.buffer!==z.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=Oe(b);if(!b)throw new FS.uc(48);z.set(a,b)}else c=!1,b=a.byteOffset;return{yc:b,od:c}},Vc(a,b,c,d){N.wc.write(a,b,0,d,c,!1);return 0}}},Re=(a,b,c)=>{var d=`al ${a}`;na(a,e=>{b(new Uint8Array(e));d&&eb()},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&db()},Se=n.preloadPlugins||[],Te=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.init();var e=
!1;Se.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Ue=a=>{var b={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[a];if("undefined"==typeof b)throw Error(`Unknown file open mode: ${a}`);return b},Ve=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},We={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,
EMFILE:33,ENOTTY:59,ETXTBSY:74,EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,
EBADFD:127,EREMCHG:128,ELIBACC:129,ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,
ENOTCONN:53,ETOOMANYREFS:141,EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};function P(a){try{return a()}catch(b){if(!b.code)throw b;if("UNKNOWN"===b.code)throw new FS.uc(28);throw new FS.uc(We[b.code]);}}function Xe(a){var b;return P(()=>{b=fs.lstatSync(a);NODEFS.Bd&&(b.mode|=(b.mode&292)>>2);return b.mode})}
function Ye(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.mount.Wd.root);b.reverse();return xe(...b)}function Ze(a){a&=-2721793;var b=0,c;for(c in NODEFS.Rd)a&c&&(b|=NODEFS.Rd[c],a^=c);if(a)throw new FS.uc(28);return b}
var NODEFS={Bd:!1,Id(){NODEFS.Bd=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);NODEFS.Rd={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,256:a.O_NOCTTY,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY,131072:a.O_NOFOLLOW}},mount(a){return NODEFS.createNode(null,"/",Xe(a.Wd.root),0)},createNode(a,b,c){if(!FS.isDir(c)&&!FS.isFile(c)&&!FS.isLink(c))throw new FS.uc(28);a=FS.createNode(a,b,c);a.xc=NODEFS.xc;a.wc=NODEFS.wc;return a},xc:{Lc(a){var b=Ye(a),
c;P(()=>c=fs.lstatSync(b));NODEFS.Bd&&(c.Yc||(c.Yc=4096),c.blocks||(c.blocks=(c.size+c.Yc-1)/c.Yc|0),c.mode|=(c.mode&292)>>2);return{dev:c.dev,ino:c.ino,mode:c.mode,nlink:c.nlink,uid:c.uid,gid:c.gid,rdev:c.rdev,size:c.size,atime:c.atime,mtime:c.mtime,ctime:c.ctime,Yc:c.Yc,blocks:c.blocks}},Fc(a,b){var c=Ye(a);P(()=>{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode);void 0!==b.size&&fs.truncateSync(c,b.size)})},lookup(a,b){var c=ye(Ye(a),b);c=Xe(c);return NODEFS.createNode(a,b,c)},Mc(a,b,c,d){var e=
NODEFS.createNode(a,b,c,d),f=Ye(e);P(()=>{FS.isDir(e.mode)?fs.mkdirSync(f,e.mode):fs.writeFileSync(f,"",{mode:e.mode})});return e},rename(a,b,c){var d=Ye(a),e=ye(Ye(b),c);P(()=>fs.renameSync(d,e));a.name=c},unlink(a,b){var c=ye(Ye(a),b);P(()=>fs.unlinkSync(c))},rmdir(a,b){var c=ye(Ye(a),b);P(()=>fs.rmdirSync(c))},readdir(a){var b=Ye(a);return P(()=>fs.readdirSync(b))},symlink(a,b,c){var d=ye(Ye(a),b);P(()=>fs.symlinkSync(c,d))},readlink(a){var b=Ye(a);return P(()=>fs.readlinkSync(b))}},wc:{open(a){var b=
Ye(a.node);P(()=>{FS.isFile(a.node.mode)&&(a.Oc.Yd=1,a.Jc=fs.openSync(b,Ze(a.flags)))})},close(a){P(()=>{FS.isFile(a.node.mode)&&a.Jc&&0===--a.Oc.Yd&&fs.closeSync(a.Jc)})},je(a){a.Oc.Yd++},read(a,b,c,d,e){return 0===d?0:P(()=>fs.readSync(a.Jc,new Int8Array(b.buffer,c,d),0,d,e))},write(a,b,c,d,e){return P(()=>fs.writeSync(a.Jc,new Int8Array(b.buffer,c,d),0,d,e))},llseek(a,b,c){var d=b;1===c?d+=a.position:2===c&&FS.isFile(a.node.mode)&&P(()=>{d+=fs.fstatSync(a.Jc).size});if(0>d)throw new FS.uc(28);
return d},Pc(a,b,c){if(!FS.isFile(a.node.mode))throw new FS.uc(43);var d=Oe(b);NODEFS.wc.read(a,z,d,b,c);return{yc:d,od:!0}},Vc(a,b,c,d){NODEFS.wc.write(a,b,0,d,c,!1);return 0}}},af={init(a,b,c){function d(f){return function(...g){try{return f(...g)}catch(h){if(h.code)throw new FS.uc(We[h.code]);throw h;}}}$e.init(a,b,c);for(var e in af)FS[e]=d(af[e])},lookup(a,b){return FS.lookupPath(`${a.path}/${b}`).node},lookupPath(a,b={}){b.parent&&(a=x.dirname(a));b=fs.lstatSync(a);var c=Xe(a);return{path:a,
node:{id:b.ino,mode:c,xc:af,path:a}}},cwd(){return process.cwd()},chdir(...a){process.chdir(...a)},Mc(a,b){FS.isDir(a)?fs.mkdirSync(a,b):fs.writeFileSync(a,"",{mode:b})},mkdir(...a){fs.mkdirSync(...a)},symlink(...a){fs.symlinkSync(...a)},rename(...a){fs.renameSync(...a)},rmdir(...a){fs.rmdirSync(...a)},readdir(...a){return[".",".."].concat(fs.readdirSync(...a))},unlink(...a){fs.unlinkSync(...a)},readlink(...a){return fs.readlinkSync(...a)},stat(...a){return fs.statSync(...a)},lstat(...a){return fs.lstatSync(...a)},
chmod(...a){fs.chmodSync(...a)},fchmod(a,b){a=Q(a);fs.fchmodSync(a.Jc,b)},chown(...a){fs.chownSync(...a)},fchown(a,b,c){a=Q(a);fs.fchownSync(a.Jc,b,c)},truncate(...a){fs.truncateSync(...a)},ftruncate(a,b){if(0>b)throw new FS.uc(28);a=Q(a);fs.ftruncateSync(a.Jc,b)},utime(){},open(a,b,c){"string"==typeof b&&(b=Ue(b));var d=a.split("/").map(function(f){return f.substr(0,255)}).join("/");c=fs.openSync(d,Ze(b),c);var e=fs.fstatSync(c);if(b&65536&&!e.isDirectory())throw fs.closeSync(c),new FS.uc(We.Ue);
d=Xe(d);return FS.hd({Jc:c,position:0,path:a,flags:b,node:{id:e.ino,mode:d,xc:af,path:a},seekable:!0})},hd(a,b){a=$e.hd(a,b);"undefined"==typeof a.Oc.Hd?a.Oc.Hd=1:a.Oc.Hd++;return a},close(a){FS.streams[a.fd]=null;a.wc||0!==--a.Oc.Hd||fs.closeSync(a.Jc)},llseek(a,b,c){if(a.wc)return $e.llseek(a,b,c);if(1===c)b+=a.position;else if(2===c)b+=fs.fstatSync(a.Jc).size;else if(0!==c)throw new FS.uc(28);if(0>b)throw new FS.uc(28);return a.position=b},read(a,b,c,d,e){if(a.wc)return $e.read(a,b,c,d,e);var f=
"undefined"!=typeof e;!f&&a.seekable&&(e=a.position);b=fs.readSync(a.Jc,new Int8Array(b.buffer,c,d),0,d,e);f||(a.position+=b);return b},write(a,b,c,d,e){if(a.wc)return $e.write(a,b,c,d,e);a.flags&1024&&FS.llseek(a,0,2);var f="undefined"!=typeof e;!f&&a.seekable&&(e=a.position);b=fs.writeSync(a.Jc,new Int8Array(b.buffer,c,d),0,d,e);f||(a.position+=b);return b},dd(){throw new FS.uc(138);},Pc(a,b,c,d,e){if(a.wc)return $e.Pc(a,b,c,d,e);d=Oe(b);FS.read(a,z,d,b,c);return{yc:d,od:!0}},Vc(a,b,c,d,e){if(a.wc)return $e.Vc(a,
b,c,d,e);FS.write(a,b,0,d,c);return 0},pd(){throw new FS.uc(59);}};function Qe(a,b){var c=FS.isDir(a.mode)?(c=bf(a,"x"))?c:a.xc.lookup?0:2:54;if(c)throw new FS.uc(c);for(c=FS.Qc[cf(a.id,b)];c;c=c.$c){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.lookup(a,b)}function Q(a){a=FS.Sd(a);if(!a)throw new FS.uc(8);return a}function cf(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.Qc.length}
function df(a){var b=cf(a.parent.id,a.name);a.$c=FS.Qc[b];FS.Qc[b]=a}function ef(a){var b=cf(a.parent.id,a.name);if(FS.Qc[b]===a)FS.Qc[b]=a.$c;else for(b=FS.Qc[b];b;){if(b.$c===a){b.$c=a.$c;break}b=b.$c}}function ff(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function bf(a,b){if(FS.Ud)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}
function gf(a,b){try{return Qe(a,b),20}catch(c){}return bf(a,"wx")}function hf(a,b,c){try{var d=Qe(a,b)}catch(e){return e.Bc}if(a=bf(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.rd(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function jf(a,b=-1){a=FS.hd(a,b);a.wc?.je?.(a);return a}function kf(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.kd)}return b}
function lf(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g});FS.mkdev("/dev/null",FS.makedev(1,3));Je(FS.makedev(5,0),Le);Je(FS.makedev(6,0),Me);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ae(a).byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")}
function mf(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.xc={lookup(c,d){var e=Q(+d);c={parent:null,mount:{Vd:"fake"},xc:{readlink:()=>e.path}};return c.parent=c}};return b}},{},"/proc/self/fd")}function nf(a,b,c,d){a=ye("string"==typeof a?a:FS.getPath(a),b);return FS.create(a,Ve(c,d))}
function of(a){if(!(a.we||a.xe||a.link||a.zc)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ma)try{a.zc=He(ma(a.url),!0),a.Cc=a.zc.length}catch(b){throw new FS.uc(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
var FS={root:null,kd:[],Pd:{},streams:[],ze:1,Qc:null,Nd:"/",zd:!1,Ud:!0,uc:class{constructor(a){this.name="ErrnoError";this.Bc=a}},xd:{},me:null,td:0,ce:class{constructor(){this.Oc={};this.node=null}get object(){return this.node}set object(a){this.node=a}get flags(){return this.Oc.flags}set flags(a){this.Oc.flags=a}get position(){return this.Oc.position}set position(a){this.Oc.position=a}},be:class{constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.Nc=null;this.id=FS.ze++;this.name=
b;this.mode=c;this.xc={};this.wc={};this.rdev=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get xe(){return FS.isDir(this.mode)}get we(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){a=Be(a);if(!a)return{path:"",node:null};b=Object.assign({wd:!0,Gd:0},b);if(8<b.Gd)throw new FS.uc(32);a=a.split("/").filter(g=>!!g);for(var c=FS.root,d="/",e=0;e<a.length;e++){var f=e===
a.length-1;if(f&&b.parent)break;c=Qe(c,a[e]);d=ye(d,a[e]);c.Nc&&(!f||f&&b.wd)&&(c=c.Nc.root);if(!f||b.follow)for(f=0;FS.isLink(c.mode);)if(c=FS.readlink(d),d=Be(x.dirname(d),c),c=FS.lookupPath(d,{Gd:b.Gd+1}).node,40<f++)throw new FS.uc(32);}return{path:d,node:c}},getPath(a){for(var b;;){if(FS.rd(a))return a=a.mount.Vd,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.be(a,b,c,d);df(a);return a},rd(a){return a===a.parent},isFile(a){return 32768===
(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},de:4096,Sd:a=>FS.streams[a],hd(a,b=-1){a=Object.assign(new FS.ce,a);if(-1==b)a:{for(b=0;b<=FS.de;b++)if(!FS.streams[b])break a;throw new FS.uc(33);}a.fd=b;return FS.streams[b]=a},ge:{open(a){a.wc=FS.oe(a.node.rdev).wc;a.wc.open?.(a)},llseek(){throw new FS.uc(70);}},Cd:a=>
a>>8,df:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Pd[a]={wc:b}},oe:a=>FS.Pd[a],syncfs(a,b){function c(g){FS.td--;return b(g)}function d(g){if(g){if(!d.ke)return d.ke=!0,c(g)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.td++;1<FS.td&&y(`warning: ${FS.td} FS.syncfs operations in flight at once, probably just doing extra work`);var e=kf(FS.root.mount),f=0;e.forEach(g=>{if(!g.type.syncfs)return d(null);g.type.syncfs(g,a,d)})},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.uc(10);
if(!d&&c){var e=FS.lookupPath(c,{wd:!1});c=e.path;e=e.node;if(e.Nc)throw new FS.uc(10);if(!FS.isDir(e.mode))throw new FS.uc(54);}b={type:a,Wd:b,Vd:c,kd:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.Nc=b,e.mount&&e.mount.kd.push(b));return a},unmount(a){a=FS.lookupPath(a,{wd:!1});if(!a.node.Nc)throw new FS.uc(28);a=a.node;var b=a.Nc,c=kf(b);Object.keys(FS.Qc).forEach(d=>{for(d=FS.Qc[d];d;){var e=d.$c;c.includes(d.mount)&&ef(d);d=e}});a.Nc=null;a.mount.kd.splice(a.mount.kd.indexOf(b),1)},lookup(a,
b){return a.xc.lookup(a,b)},Mc(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=x.basename(a);if(!a||"."===a||".."===a)throw new FS.uc(28);var e=gf(d,a);if(e)throw new FS.uc(e);if(!d.xc.Mc)throw new FS.uc(63);return d.xc.Mc(d,a,b,c)},create(a,b){return FS.Mc(a,(void 0!==b?b:438)&4095|32768,0)},mkdir(a,b){return FS.Mc(a,(void 0!==b?b:511)&1023|16384,0)},ef(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{FS.mkdir(c,b)}catch(e){if(20!=e.Bc)throw e;}}},mkdev(a,b,c){"undefined"==
typeof c&&(c=b,b=438);return FS.Mc(a,b|8192,c)},symlink(a,b){if(!Be(a))throw new FS.uc(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.uc(44);b=x.basename(b);var d=gf(c,b);if(d)throw new FS.uc(d);if(!c.xc.symlink)throw new FS.uc(63);return c.xc.symlink(c,b,a)},rename(a,b){var c=x.dirname(a),d=x.dirname(b),e=x.basename(a),f=x.basename(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.uc(44);if(h.mount!==g.mount)throw new FS.uc(75);
var k=Qe(h,e);a=Ce(a,d);if("."!==a.charAt(0))throw new FS.uc(28);a=Ce(b,c);if("."!==a.charAt(0))throw new FS.uc(55);try{var m=Qe(g,f)}catch(p){}if(k!==m){b=FS.isDir(k.mode);if(e=hf(h,e,b))throw new FS.uc(e);if(e=m?hf(g,f,b):gf(g,f))throw new FS.uc(e);if(!h.xc.rename)throw new FS.uc(63);if(k.Nc||m&&m.Nc)throw new FS.uc(10);if(g!==h&&(e=bf(h,"w")))throw new FS.uc(e);ef(k);try{h.xc.rename(k,g,f),k.parent=g}catch(p){throw p;}finally{df(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=x.basename(a);
var c=Qe(b,a),d=hf(b,a,!0);if(d)throw new FS.uc(d);if(!b.xc.rmdir)throw new FS.uc(63);if(c.Nc)throw new FS.uc(10);b.xc.rmdir(b,a);ef(c)},readdir(a){a=FS.lookupPath(a,{follow:!0}).node;if(!a.xc.readdir)throw new FS.uc(54);return a.xc.readdir(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.uc(44);a=x.basename(a);var c=Qe(b,a),d=hf(b,a,!1);if(d)throw new FS.uc(d);if(!b.xc.unlink)throw new FS.uc(63);if(c.Nc)throw new FS.uc(10);b.xc.unlink(b,a);ef(c)},readlink(a){a=FS.lookupPath(a).node;
if(!a)throw new FS.uc(44);if(!a.xc.readlink)throw new FS.uc(28);return Be(FS.getPath(a.parent),a.xc.readlink(a))},stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;if(!a)throw new FS.uc(44);if(!a.xc.Lc)throw new FS.uc(63);return a.xc.Lc(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;if(!a.xc.Fc)throw new FS.uc(63);a.xc.Fc(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=Q(a);FS.chmod(a.node,b)},chown(a,
b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;if(!a.xc.Fc)throw new FS.uc(63);a.xc.Fc(a,{timestamp:Date.now()})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a,b,c){a=Q(a);FS.chown(a.node,b,c)},truncate(a,b){if(0>b)throw new FS.uc(28);a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;if(!a.xc.Fc)throw new FS.uc(63);if(FS.isDir(a.mode))throw new FS.uc(31);if(!FS.isFile(a.mode))throw new FS.uc(28);var c=bf(a,"w");if(c)throw new FS.uc(c);a.xc.Fc(a,{size:b,timestamp:Date.now()})},
ftruncate(a,b){a=Q(a);if(0===(a.flags&2097155))throw new FS.uc(28);FS.truncate(a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;a.xc.Fc(a,{timestamp:Math.max(b,c)})},open(a,b,c){if(""===a)throw new FS.uc(44);b="string"==typeof b?Ue(b):b;c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var d=a;else{a=x.posix.normalize(a);try{d=FS.lookupPath(a,{follow:!(b&131072)}).node}catch(g){}}var e=!1;if(b&64)if(d){if(b&128)throw new FS.uc(20);}else d=FS.Mc(a,c,0),e=!0;if(!d)throw new FS.uc(44);
FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.uc(54);if(!e){c=d;var f=b;if(c=c?FS.isLink(c.mode)?32:FS.isDir(c.mode)&&("r"!==ff(f)||f&512)?31:bf(c,ff(f)):44)throw new FS.uc(c);}b&512&&!e&&FS.truncate(d,0);b&=-131713;d=FS.hd({node:d,path:FS.getPath(d),flags:b,seekable:!0,position:0,wc:d.wc,Re:[],error:!1});d.wc.open&&d.wc.open(d);!n.logReadFiles||b&1||(FS.Fd||(FS.Fd={}),a in FS.Fd||(FS.Fd[a]=1));return d},close(a){if(null===a.fd)throw new FS.uc(8);a.yd&&(a.yd=null);try{a.wc.close&&
a.wc.close(a)}catch(b){throw b;}finally{FS.streams[a.fd]=null}a.fd=null},llseek(a,b,c){if(null===a.fd)throw new FS.uc(8);if(!a.seekable||!a.wc.llseek)throw new FS.uc(70);if(0!=c&&1!=c&&2!=c)throw new FS.uc(28);a.position=a.wc.llseek(a,b,c);a.Re=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.uc(28);if(null===a.fd)throw new FS.uc(8);if(1===(a.flags&2097155))throw new FS.uc(8);if(FS.isDir(a.node.mode))throw new FS.uc(31);if(!a.wc.read)throw new FS.uc(28);var f="undefined"!=typeof e;if(!f)e=
a.position;else if(!a.seekable)throw new FS.uc(70);b=a.wc.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.uc(28);if(null===a.fd)throw new FS.uc(8);if(0===(a.flags&2097155))throw new FS.uc(8);if(FS.isDir(a.node.mode))throw new FS.uc(31);if(!a.wc.write)throw new FS.uc(28);a.seekable&&a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.uc(70);b=a.wc.write(a,b,c,d,e,f);g||(a.position+=b);return b},dd(a,
b,c){if(null===a.fd)throw new FS.uc(8);if(0>b||0>=c)throw new FS.uc(28);if(0===(a.flags&2097155))throw new FS.uc(8);if(!FS.isFile(a.node.mode)&&!FS.isDir(a.node.mode))throw new FS.uc(43);if(!a.wc.dd)throw new FS.uc(138);a.wc.dd(a,b,c)},Pc(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.uc(2);if(1===(a.flags&2097155))throw new FS.uc(2);if(!a.wc.Pc)throw new FS.uc(43);return a.wc.Pc(a,b,c,d,e)},Vc(a,b,c,d,e){return a.wc.Vc?a.wc.Vc(a,b,c,d,e):0},pd(a,b,c){if(!a.wc.pd)throw new FS.uc(59);
return a.wc.pd(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=FS.open(a,b.flags);a=FS.stat(a).size;var e=new Uint8Array(a);FS.read(d,e,0,a,0);"utf8"===b.encoding?c=De(e):"binary"===b.encoding&&(c=e);FS.close(d);return c},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Fe(b)+1);b=Ge(b,d,0,d.length);FS.write(a,
d,0,b,void 0,c.fe)}else if(ArrayBuffer.isView(b))FS.write(a,b,0,b.byteLength,void 0,c.fe);else throw Error("Unsupported data type");FS.close(a)},cwd:()=>FS.Nd,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.uc(44);if(!FS.isDir(a.node.mode))throw new FS.uc(54);var b=bf(a.node,"x");if(b)throw new FS.uc(b);FS.Nd=a.path},Id(){[44].forEach(a=>{FS.xd[a]=new FS.uc(a);FS.xd[a].stack="<generic error, no stack>"});FS.Qc=Array(4096);FS.mount(N,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");
FS.mkdir("/home/web_user");lf();mf();FS.me={MEMFS:N,NODEFS}},init(a,b,c){FS.init.zd=!0;n.stdin=a||n.stdin;n.stdout=b||n.stdout;n.stderr=c||n.stderr;n.stdin?FS.createDevice("/dev","stdin",n.stdin):FS.symlink("/dev/tty","/dev/stdin");n.stdout?FS.createDevice("/dev","stdout",null,n.stdout):FS.symlink("/dev/tty","/dev/stdout");n.stderr?FS.createDevice("/dev","stderr",null,n.stderr):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},$e(a,b){a=
FS.analyzePath(a,b);return a.exists?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={rd:!1,exists:!1,error:0,name:null,path:null,object:null,Ae:!1,Ce:null,Be:null};try{c=FS.lookupPath(a,{parent:!0}),d.Ae=!0,d.Ce=c.path,d.Be=c.node,d.name=x.basename(a),c=FS.lookupPath(a,{follow:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.rd="/"===c.path}catch(e){d.error=e.Bc}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);for(b=
b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=ye(a,c);try{FS.mkdir(d)}catch(e){}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?ye(a,b):a);a=Ve(d,e);g=FS.create(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}FS.chmod(g,a|146);b=FS.open(g,577);FS.write(b,c,0,c.length,0,f);FS.close(b);FS.chmod(g,a)}},createDevice(a,b,c,d){a=ye("string"==typeof a?a:FS.getPath(a),b);b=Ve(!!c,!!d);FS.createDevice.Cd||
(FS.createDevice.Cd=64);var e=FS.makedev(FS.createDevice.Cd++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,k){for(var m=0,p=0;p<k;p++){try{var q=c()}catch(r){throw new FS.uc(29);}if(void 0===q&&0===m)throw new FS.uc(6);if(null===q||void 0===q)break;m++;g[h+p]=q}m&&(f.node.timestamp=Date.now());return m},write(f,g,h,k){for(var m=0;m<k;m++)try{d(g[h+m])}catch(p){throw new FS.uc(29);}k&&(f.node.timestamp=Date.now());return m}});return FS.mkdev(a,b,e)},createLazyFile(a,
b,c,d,e){function f(q,r,l,t,v){q=q.node.zc;if(v>=q.length)return 0;t=Math.min(q.length-v,t);if(q.slice)for(var G=0;G<t;G++)r[l+G]=q[v+G];else for(G=0;G<t;G++)r[l+G]=q.get(v+G);return t}class g{constructor(){this.Kd=!1;this.Uc=[];this.jd=void 0;this.Zd=this.$d=0}get(q){if(!(q>this.length-1||0>q)){var r=q%this.chunkSize;return this.jd(q/this.chunkSize|0)[r]}}Te(q){this.jd=q}ae(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+
c+". Status: "+q.status);var r=Number(q.getResponseHeader("Content-length")),l,t=(l=q.getResponseHeader("Accept-Ranges"))&&"bytes"===l;q=(l=q.getResponseHeader("Content-Encoding"))&&"gzip"===l;var v=1048576;t||(v=r);var G=this;G.Te(O=>{var K=O*v,V=(O+1)*v-1;V=Math.min(V,r-1);if("undefined"==typeof G.Uc[O]){var Xa=G.Uc;if(K>V)throw Error("invalid range ("+K+", "+V+") or no bytes requested!");if(V>r-1)throw Error("only "+r+" bytes available! programmer error!");var T=new XMLHttpRequest;T.open("GET",
c,!1);r!==v&&T.setRequestHeader("Range","bytes="+K+"-"+V);T.responseType="arraybuffer";T.overrideMimeType&&T.overrideMimeType("text/plain; charset=x-user-defined");T.send(null);if(!(200<=T.status&&300>T.status||304===T.status))throw Error("Couldn't load "+c+". Status: "+T.status);K=void 0!==T.response?new Uint8Array(T.response||[]):He(T.responseText||"",!0);Xa[O]=K}if("undefined"==typeof G.Uc[O])throw Error("doXHR failed!");return G.Uc[O]});if(q||!r)v=r=1,v=r=this.jd(0).length,sa("LazyFiles on gzip forces download of the whole file when length is accessed");
this.$d=r;this.Zd=v;this.Kd=!0}get length(){this.Kd||this.ae();return this.$d}get chunkSize(){this.Kd||this.ae();return this.Zd}}if("undefined"!=typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var k=void 0}else k=c,h=void 0;var m=nf(a,b,d,e);h?m.zc=h:k&&(m.zc=null,m.url=k);Object.defineProperties(m,{Cc:{get:function(){return this.zc.length}}});var p={};Object.keys(m.wc).forEach(q=>
{var r=m.wc[q];p[q]=(...l)=>{of(m);return r(...l)}});p.read=(q,r,l,t,v)=>{of(m);return f(q,r,l,t,v)};p.Pc=(q,r,l)=>{of(m);var t=Oe(r);if(!t)throw new FS.uc(48);f(q,z,t,r,l);return{yc:t,od:!0}};m.wc=p;return m}},pf=5;function qf(a,b,c){if(x.isAbsolute(b))return b;a=-100===a?FS.cwd():Q(a).path;if(0==b.length){if(!c)throw new FS.uc(44);return a}return ye(a,b)}
function rf(a,b,c){a=a(b);C[c>>2]=a.dev;C[c+4>>2]=a.mode;D[c+8>>2]=a.nlink;C[c+12>>2]=a.uid;C[c+16>>2]=a.gid;C[c+20>>2]=a.rdev;E[c+24>>3]=BigInt(a.size);C[c+32>>2]=4096;C[c+36>>2]=a.blocks;b=a.atime.getTime();var d=a.mtime.getTime(),e=a.ctime.getTime();E[c+40>>3]=BigInt(Math.floor(b/1E3));D[c+48>>2]=b%1E3*1E3;E[c+56>>3]=BigInt(Math.floor(d/1E3));D[c+64>>2]=d%1E3*1E3;E[c+72>>3]=BigInt(Math.floor(e/1E3));D[c+80>>2]=e%1E3*1E3;E[c+88>>3]=BigInt(a.ino);return 0}var sf=void 0;
function yb(a){if(w)return L(3,1,a);try{var b=Q(a);return jf(b).fd}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Bc}}function zb(a,b,c,d){if(w)return L(4,1,a,b,c,d);try{b=M(b);b=qf(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&bf(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.Bc}}function tf(){var a=C[+sf>>2];sf+=4;return a}
function Ab(a,b,c){if(w)return L(5,1,a,b,c);sf=c;try{var d=Q(a);switch(b){case 0:var e=tf();if(0>e)break;for(;FS.streams[e];)e++;return jf(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=tf(),d.flags|=e,0;case 12:return e=tf(),Na[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.Bc}}
function Bb(a,b){if(w)return L(6,1,a,b);try{var c=Q(a);return rf(FS.stat,c.path,b)}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.Bc}}function Cb(a,b){if(w)return L(7,1,a,b);b=ae(b);try{if(isNaN(b))return 61;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Bc}}
function Db(a,b){if(w)return L(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=Fe(c)+1;if(b<d)return-68;Ge(c,A,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.Bc}}
function Eb(a,b,c){if(w)return L(9,1,a,b,c);sf=c;try{var d=Q(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Wc.te){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=tf();C[e>>2]=25856;C[e+4>>2]=5;C[e+8>>2]=191;C[e+12>>2]=35387;for(var f=0;32>f;f++)z[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Wc.ue)for(e=tf(),a=[],f=0;32>f;f++)a.push(z[e+
f+17]);return 0;case 21519:if(!d.tty)return-59;e=tf();return C[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return e=tf(),FS.pd(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Wc.ve&&(f=[24,80],e=tf(),Na[e>>1]=f[0],Na[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.Bc}}
function Fb(a,b){if(w)return L(10,1,a,b);try{return a=M(a),rf(FS.lstat,a,b)}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Bc}}function Gb(a,b,c,d){if(w)return L(11,1,a,b,c,d);try{b=M(b);var e=d&256;b=qf(a,b,d&4096);return rf(e?FS.lstat:FS.stat,b,c)}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.Bc}}
function Hb(a,b,c,d){if(w)return L(12,1,a,b,c,d);sf=d;try{b=M(b);b=qf(a,b);var e=d?tf():0;return FS.open(b,c,e).fd}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.Bc}}function Ib(a,b,c){if(w)return L(13,1,a,b,c);try{for(var d=c=0;d<b;d++){var e=a+8*d,f=Na[e+4>>1],g=32,h=FS.Sd(C[e>>2]);h&&(g=pf,h.wc.Ee&&(g=h.wc.Ee(h,-1)));(g&=f|24)&&c++;Na[e+6>>1]=g}return c}catch(k){if("undefined"==typeof FS||"ErrnoError"!==k.name)throw k;return-k.Bc}}
function Jb(a){if(w)return L(14,1,a);try{return a=M(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.Bc}}function Kb(a,b){if(w)return L(15,1,a,b);try{return a=M(a),rf(FS.stat,a,b)}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.Bc}}
function Lb(a,b,c){if(w)return L(16,1,a,b,c);try{return b=M(b),b=qf(a,b),0===c?FS.unlink(b):512===c?FS.rmdir(b):fb("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.Bc}}var Mb=()=>{fb("")},uf={},vf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function wf(a){return this.fromWireType(D[a>>2])}
var xf={},yf={},zf={},Af,Cf=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new Af("Mismatched type converter count");for(var k=0;k<a.length;++k)Bf(a[k],h[k])}a.forEach(function(h){zf[h]=b});var e=Array(b.length),f=[],g=0;b.forEach((h,k)=>{yf.hasOwnProperty(h)?e[k]=yf[h]:(f.push(h),xf.hasOwnProperty(h)||(xf[h]=[]),xf[h].push(()=>{e[k]=yf[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},Nb=a=>{var b=uf[a];delete uf[a];var c=b.Ed,d=b.Sc,e=b.Qd,f=e.map(g=>g.re).concat(e.map(g=>g.Ie));Cf([a],
f,g=>{var h={};e.forEach((k,m)=>{var p=g[m],q=k.jd,r=k.qe,l=g[m+e.length],t=k.He,v=k.Je;h[k.le]={read:G=>p.fromWireType(q(r,G)),write:(G,O)=>{var K=[];t(v,G,l.toWireType(K,O));vf(K)}}});return[{name:b.name,fromWireType:k=>{var m={},p;for(p in h)m[p]=h[p].read(k);d(k);return m},toWireType:(k,m)=>{for(var p in h)if(!(p in m))throw new TypeError(`Missing field: "${p}"`);var q=c();for(p in h)h[p].write(q,m[p]);null!==k&&k.push(d,q);return q},argPackAdvance:Df,readValueFromPointer:wf,Hc:d}]})},Ef,R=a=>
{for(var b="";A[a];)b+=Ef[A[a++]];return b},S,Ff=a=>{throw new S(a);};function Gf(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(yf.hasOwnProperty(a)){if(c.se)return;throw new S(`Cannot register type '${d}' twice`);}yf[a]=b;delete zf[a];xf.hasOwnProperty(a)&&(b=xf[a],delete xf[a],b.forEach(e=>e()))}
function Bf(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return Gf(a,b,c)}
var Ob=(a,b,c,d,e)=>{b=R(b);if(d)a:switch(c){case 4:d=Oa;break a;case 8:d=Qa;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?z:A;break a;case 2:d=e?Na:B;break a;case 4:d=e?C:D;break a;case 8:d=e?E:Pa;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);Bf(a,{name:b,fromWireType:h=>{for(var k=D[h>>2],m=Array(k),p=h+Math.max(4,c)>>g,q=0;q<k;++q)m[q]=f[p+q];U(h);return m},toWireType:(h,k)=>{"number"==typeof k&&
(k=[k]);if(!Array.isArray(k))throw new S("Cannot pass non-array to C++ vector type "+b);k=Array.prototype.concat.apply([],k);var m=k.length,p=Math.max(4,c),q=Hf(p+m*c);p=q+p>>g;D[q>>2]=m;f.set(k,p);null!==h&&h.push(U,q);return q},argPackAdvance:Df,readValueFromPointer:wf,Hc(h){U(h)}})},If=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Jf=(a,b,c)=>{switch(b){case 1:return c?d=>z[d]:d=>A[d];case 2:return c?d=>Na[d>>1]:d=>B[d>>1];case 4:return c?
d=>C[d>>2]:d=>D[d>>2];case 8:return c?d=>E[d>>3]:d=>Pa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Pb=(a,b,c)=>{b=R(b);var d=b.includes("u");Bf(a,{name:b,fromWireType:e=>e,toWireType:function(e,f){if("bigint"!=typeof f&&"number"!=typeof f)throw new TypeError(`Cannot convert "${If(f)}" to ${this.name}`);"number"==typeof f&&(f=BigInt(f));return f},argPackAdvance:Df,readValueFromPointer:Jf(b,c,!d),Hc:null})},Df=8,Qb=(a,b,c,d)=>{b=R(b);Bf(a,{name:b,fromWireType:function(e){return!!e},
toWireType:function(e,f){return f?c:d},argPackAdvance:Df,readValueFromPointer:function(e){return this.fromWireType(A[e])},Hc:null})},Kf=a=>{throw new S(a.vc.Dc.Ac.name+" instance already deleted");},Lf=!1,Mf=!1,Nf=()=>{},Of=(a,b,c)=>{if(b===c)return a;if(void 0===c.Ic)return null;a=Of(a,b,c.Ic);return null===a?null:c.ie(a)},Pf={},Qf=[],Rf=()=>{for(;Qf.length;){var a=Qf.pop();a.vc.gd=!1;a["delete"]()}},Sf,Tf={},Uf=(a,b)=>{if(void 0===b)throw new S("ptr should not be undefined");for(;a.Ic;)b=a.md(b),
a=a.Ic;return Tf[b]},Wf=(a,b)=>{if(!b.Dc||!b.yc)throw new Af("makeClassHandle requires ptr and ptrType");if(!!b.Kc!==!!b.Gc)throw new Af("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Vf(Object.create(a,{vc:{value:b,writable:!0}}))},Vf=a=>{if(Lf)return Vf=b=>b.deleteLater(),Vf(a);if("undefined"===typeof FinalizationRegistry)return Vf=b=>b,a;Mf=new FinalizationRegistry(b=>{b=b.vc;--b.count.value;0===b.count.value&&(b.Gc?b.Kc.Sc(b.Gc):b.Dc.Ac.Sc(b.yc))});Vf=b=>{var c=b.vc;
c.Gc&&Mf.register(b,{vc:c},b);return b};Nf=b=>{Mf.unregister(b)};return Vf(a)};function Xf(){}
var Yf=(a,b)=>Object.defineProperty(b,"name",{value:a}),Zf=(a,b,c)=>{if(void 0===a[b].Ec){var d=a[b];a[b]=function(...e){if(!a[b].Ec.hasOwnProperty(e.length))throw new S(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Ec})!`);return a[b].Ec[e.length].apply(this,e)};a[b].Ec=[];a[b].Ec[d.ed]=d}},$f=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].Ec&&void 0!==n[a].Ec[c])throw new S(`Cannot register public name '${a}' twice`);Zf(n,a,a);
if(n.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);n[a].Ec[c]=b}else n[a]=b,void 0!==c&&(n[a].ff=c)},ag=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function bg(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.Xc=c;this.Sc=d;this.Ic=e;this.ne=f;this.md=g;this.ie=h;this.Fe=[]}
var cg=(a,b,c)=>{for(;b!==c;){if(!b.md)throw new S(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.md(a);b=b.Ic}return a};function dg(a,b){if(null===b){if(this.Ad)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.vc)throw new S(`Cannot pass "${If(b)}" as a ${this.name}`);if(!b.vc.yc)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);return cg(b.vc.yc,b.vc.Dc.Ac,this.Ac)}
function eg(a,b){if(null===b){if(this.Ad)throw new S(`null is not a valid ${this.name}`);if(this.sd){var c=this.Ed();null!==a&&a.push(this.Sc,c);return c}return 0}if(!b||!b.vc)throw new S(`Cannot pass "${If(b)}" as a ${this.name}`);if(!b.vc.yc)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.qd&&b.vc.Dc.qd)throw new S(`Cannot convert argument of type ${b.vc.Kc?b.vc.Kc.name:b.vc.Dc.name} to parameter type ${this.name}`);c=cg(b.vc.yc,b.vc.Dc.Ac,this.Ac);if(this.sd){if(void 0===
b.vc.Gc)throw new S("Passing raw pointer to smart pointer is illegal");switch(this.Ke){case 0:if(b.vc.Kc===this)c=b.vc.Gc;else throw new S(`Cannot convert argument of type ${b.vc.Kc?b.vc.Kc.name:b.vc.Dc.name} to parameter type ${this.name}`);break;case 1:c=b.vc.Gc;break;case 2:if(b.vc.Kc===this)c=b.vc.Gc;else{var d=b.clone();c=this.Ge(c,fg(()=>d["delete"]()));null!==a&&a.push(this.Sc,c)}break;default:throw new S("Unsupporting sharing policy");}}return c}
function gg(a,b){if(null===b){if(this.Ad)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.vc)throw new S(`Cannot pass "${If(b)}" as a ${this.name}`);if(!b.vc.yc)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.vc.Dc.qd)throw new S(`Cannot convert argument of type ${b.vc.Dc.name} to parameter type ${this.name}`);return cg(b.vc.yc,b.vc.Dc.Ac,this.Ac)}
function hg(a,b,c,d,e,f,g,h,k,m,p){this.name=a;this.Ac=b;this.Ad=c;this.qd=d;this.sd=e;this.De=f;this.Ke=g;this.Xd=h;this.Ed=k;this.Ge=m;this.Sc=p;e||void 0!==b.Ic?this.toWireType=eg:(this.toWireType=d?dg:gg,this.Hc=null)}
var ig=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new Af("Replacing nonexistent public symbol");void 0!==n[a].Ec&&void 0!==c?n[a].Ec[c]=b:(n[a]=b,n[a].ed=c)},W=(a,b)=>{a=R(a);var c=J.get(b);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);return c},jg,lg=a=>{a=kg(a);var b=R(a);U(a);return b},mg=(a,b)=>{function c(f){e[f]||yf[f]||(zf[f]?zf[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new jg(`${a}: `+d.map(lg).join([", "]));},Rb=(a,b,c,d,
e,f,g,h,k,m,p,q,r)=>{p=R(p);f=W(e,f);h&&=W(g,h);m&&=W(k,m);r=W(q,r);var l=ag(p);$f(l,function(){mg(`Cannot construct ${p} due to unbound types`,[d])});Cf([a,b,c],d?[d]:[],t=>{t=t[0];if(d){var v=t.Ac;var G=v.Xc}else G=Xf.prototype;t=Yf(p,function(...Xa){if(Object.getPrototypeOf(this)!==O)throw new S("Use 'new' to construct "+p);if(void 0===K.Zc)throw new S(p+" has no accessible constructor");var T=K.Zc[Xa.length];if(void 0===T)throw new S(`Tried to invoke ctor of ${p} with invalid number of parameters (${Xa.length}) - expected (${Object.keys(K.Zc).toString()}) parameters instead!`);
return T.apply(this,Xa)});var O=Object.create(G,{constructor:{value:t}});t.prototype=O;var K=new bg(p,t,O,r,v,f,h,m);if(K.Ic){var V;(V=K.Ic).nd??(V.nd=[]);K.Ic.nd.push(K)}v=new hg(p,K,!0,!1,!1);V=new hg(p+"*",K,!1,!1,!1);G=new hg(p+" const*",K,!1,!0,!1);Pf[a]={pointerType:V,he:G};ig(l,t);return[v,V,G]})};function ng(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Hc)return!0;return!1}
function og(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Yf(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function pg(a,b,c,d,e,f){var g=b.length;if(2>g)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=ng(b);c="void"!==b[0].name;d=[a,Ff,d,e,vf,b[0],b[1]];for(e=0;e<g-2;++e)d.push(b[e+2]);if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].Hc&&d.push(b[e].Hc);k=ng(b);e=b.length;var m="",p="";for(g=0;g<e-2;++g)m+=(0!==g?", ":"")+"arg"+g,p+=(0!==g?", ":"")+"arg"+g+"Wired";m=`\n        return function (${m}) {\n        if (arguments.length !== ${e-
2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${e-2}');\n        }`;k&&(m+="var destructors = [];\n");var q=k?"destructors":"null",r="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");h&&(m+="var thisWired = classParam['toWireType']("+q+", this);\n");for(g=0;g<e-2;++g)m+="var arg"+g+"Wired = argType"+g+"['toWireType']("+q+", arg"+g+");\n",r.push("argType"+g);h&&(p="thisWired"+(0<p.length?", ":
"")+p);m+=(c||f?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(k)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].Hc&&(m+=`${f}_dtor(${f});\n`,r.push(`${f}_dtor`));c&&(m+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [l,t]=[r,m+"}\n"];l.push(t);b=og(l)(...d);return Yf(a,b)}
var qg=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c},rg=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Sb=(a,b,c,d,e,f,g,h)=>{var k=qg(c,d);b=R(b);b=rg(b);f=W(e,f);Cf([],[a],m=>{function p(){mg(`Cannot call ${q} due to unbound types`,k)}m=m[0];var q=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var r=m.Ac.constructor;void 0===r[b]?(p.ed=c-1,r[b]=p):(Zf(r,b,q),r[b].Ec[c-1]=p);Cf([],k,l=>{l=[l[0],null].concat(l.slice(1));l=pg(q,l,null,f,g,h);void 0===
r[b].Ec?(l.ed=c-1,r[b]=l):r[b].Ec[c-1]=l;if(m.Ac.nd)for(const t of m.Ac.nd)t.constructor.hasOwnProperty(b)||(t.constructor[b]=l);return[]});return[]})},Tb=(a,b,c,d,e,f)=>{var g=qg(b,c);e=W(d,e);Cf([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.Ac.Zc&&(h.Ac.Zc=[]);if(void 0!==h.Ac.Zc[b-1])throw new S(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
h.Ac.Zc[b-1]=()=>{mg(`Cannot construct ${h.name} due to unbound types`,g)};Cf([],g,m=>{m.splice(1,0,null);h.Ac.Zc[b-1]=pg(k,m,null,e,f);return[]});return[]})},Ub=(a,b,c,d,e,f,g,h,k)=>{var m=qg(c,d);b=R(b);b=rg(b);f=W(e,f);Cf([],[a],p=>{function q(){mg(`Cannot call ${r} due to unbound types`,m)}p=p[0];var r=`${p.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&p.Ac.Fe.push(b);var l=p.Ac.Xc,t=l[b];void 0===t||void 0===t.Ec&&t.className!==p.name&&t.ed===c-2?(q.ed=c-2,q.className=p.name,
l[b]=q):(Zf(l,b,r),l[b].Ec[c-2]=q);Cf([],m,v=>{v=pg(r,v,p,f,g,k);void 0===l[b].Ec?(v.ed=c-2,l[b]=v):l[b].Ec[c-2]=v;return[]});return[]})},sg=(a,b,c)=>{if(!(a instanceof Object))throw new S(`${c} with invalid "this": ${a}`);if(!(a instanceof b.Ac.constructor))throw new S(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.vc.yc)throw new S(`cannot call emscripten binding method ${c} on deleted object`);return cg(a.vc.yc,a.vc.Dc.Ac,b.Ac)},Vb=(a,b,c,d,e,f,g,h,k,m)=>{b=R(b);e=W(d,e);
Cf([],[a],p=>{p=p[0];var q=`${p.name}.${b}`,r={get(){mg(`Cannot access ${q} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};r.set=k?()=>mg(`Cannot access ${q} due to unbound types`,[c,g]):()=>{throw new S(q+" is a read-only property");};Object.defineProperty(p.Ac.Xc,b,r);Cf([],k?[c,g]:[c],l=>{var t=l[0],v={get(){var O=sg(this,p,q+" getter");return t.fromWireType(e(f,O))},enumerable:!0};if(k){k=W(h,k);var G=l[1];v.set=function(O){var K=sg(this,p,q+" setter"),V=[];k(m,K,G.toWireType(V,
O));vf(V)}}Object.defineProperty(p.Ac.Xc,b,v);return[]});return[]})},tg=[],ug=[],rc=a=>{9<a&&0===--ug[a+1]&&(ug[a]=void 0,tg.push(a))},X=a=>{if(!a)throw new S("Cannot use deleted val. handle = "+a);return ug[a]},fg=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=tg.pop()||ug.length;ug[b]=a;ug[b+1]=1;return b}},vg={name:"emscripten::val",fromWireType:a=>{var b=X(a);rc(a);return b},toWireType:(a,b)=>fg(b),argPackAdvance:Df,readValueFromPointer:wf,
Hc:null},Wb=a=>Bf(a,vg),wg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.fromWireType(z[d])}:function(d){return this.fromWireType(A[d])};case 2:return c?function(d){return this.fromWireType(Na[d>>1])}:function(d){return this.fromWireType(B[d>>1])};case 4:return c?function(d){return this.fromWireType(C[d>>2])}:function(d){return this.fromWireType(D[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Xb=(a,b,c,d)=>{function e(){}b=R(b);e.values={};Bf(a,{name:b,
constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:(f,g)=>g.value,argPackAdvance:Df,readValueFromPointer:wg(b,c,d),Hc:null});$f(b,e)},xg=(a,b)=>{var c=yf[a];if(void 0===c)throw a=`${b} has unknown type ${lg(a)}`,new S(a);return c},Yb=(a,b,c)=>{var d=xg(a,"enum");b=R(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Yf(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},yg=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(Oa[c>>
2])};case 8:return function(c){return this.fromWireType(Qa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Zb=(a,b,c)=>{b=R(b);Bf(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:Df,readValueFromPointer:yg(b,c),Hc:null})},$b=(a,b,c,d,e,f,g)=>{var h=qg(b,c);a=R(a);a=rg(a);e=W(d,e);$f(a,function(){mg(`Cannot call ${a} due to unbound types`,h)},b-1);Cf([],h,k=>{k=[k[0],null].concat(k.slice(1));ig(a,pg(a,k,null,e,f,g),b-1);return[]})},ac=(a,b,c,d,e)=>{b=R(b);-1===
e&&(e=4294967295);e=h=>h;if(0===d){var f=32-8*c;e=h=>h<<f>>>f}var g=b.includes("unsigned")?function(h,k){return k>>>0}:function(h,k){return k};Bf(a,{name:b,fromWireType:e,toWireType:g,argPackAdvance:Df,readValueFromPointer:Jf(b,c,0!==d),Hc:null})},bc=(a,b,c)=>{function d(f){return new e(z.buffer,D[f+4>>2],D[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=R(c);Bf(a,{name:c,fromWireType:d,argPackAdvance:Df,
readValueFromPointer:d},{se:!0})},cc=(a,b)=>{b=R(b);var c="std::string"===b;Bf(a,{name:b,fromWireType:function(d){var e=D[d>>2],f=d+4;if(c)for(var g=f,h=0;h<=e;++h){var k=f+h;if(h==e||0==A[k]){g=M(g,k-g);if(void 0===m)var m=g;else m+=String.fromCharCode(0),m+=g;g=k+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(A[f+h]);m=m.join("")}U(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof
Uint8ClampedArray||e instanceof Int8Array))throw new S("Cannot pass non-string to std::string");var g=c&&f?Fe(e):e.length;var h=Hf(4+g+1),k=h+4;D[h>>2]=g;if(c&&f)Ge(e,A,k,g+1);else if(f)for(f=0;f<g;++f){var m=e.charCodeAt(f);if(255<m)throw U(k),new S("String has UTF-16 code units that do not fit in 8 bits");A[k+f]=m}else A.set(e,k);null!==d&&d.push(U,h);return h},argPackAdvance:Df,readValueFromPointer:wf,Hc(d){U(d)}})},zg=new TextDecoder("utf-16le"),Ag=(a,b)=>{var c=a>>1;for(b=c+b/2;!(c>=b)&&B[c];)++c;
return zg.decode(A.slice(a,c<<1))},Bg=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)Na[b>>1]=a.charCodeAt(e),b+=2;Na[b>>1]=0;return b-d},Cg=a=>2*a.length,Dg=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Eg=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);
if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d},Fg=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},dc=(a,b,c)=>{c=R(c);if(2===b){var d=Ag;var e=Bg;var f=Cg;var g=h=>B[h>>1]}else 4===b&&(d=Dg,e=Eg,f=Fg,g=h=>D[h>>2]);Bf(a,{name:c,fromWireType:h=>{for(var k=D[h>>2],m,p=h+4,q=0;q<=k;++q){var r=h+4+q*b;if(q==k||0==g(r))p=d(p,r-p),void 0===m?m=p:(m+=String.fromCharCode(0),m+=
p),p=r+b}U(h);return m},toWireType:(h,k)=>{if("string"!=typeof k)throw new S(`Cannot pass non-string to C++ string type ${c}`);var m=f(k),p=Hf(4+m+b);D[p>>2]=m/b;e(k,p+4,m+b);null!==h&&h.push(U,p);return p},argPackAdvance:Df,readValueFromPointer:wf,Hc(h){U(h)}})},ec=(a,b,c,d,e,f)=>{uf[a]={name:R(b),Ed:W(c,d),Sc:W(e,f),Qd:[]}},fc=(a,b,c,d,e,f,g,h,k,m)=>{uf[a].Qd.push({le:R(b),re:c,jd:W(d,e),qe:f,Ie:g,He:W(h,k),Je:m})},gc=(a,b)=>{b=R(b);Bf(a,{ye:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>
{}})},hc=()=>1,ic=a=>{Aa(a,!ea,1,!da,262144,!1);Da()},Ba=a=>{"function"===typeof Atomics.Se&&(Atomics.Se(C,a>>2,a).value.then(Ha),Atomics.store(C,a+128>>2,1))},Ha=()=>{var a=wa();if(a&&(Ba(a),a=Gg,!Ya&&!La))try{if(a(),!(Ya||ce||0<$d))try{w?Ga(Ma):Uc(Ma)}catch(b){ee(b)}}catch(b){ee(b)}},jc=(a,b)=>{a==b?setTimeout(Ha):w?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=Yd[a])&&a.postMessage({cmd:"checkMailbox"})},Hg=[],kc=(a,b,c,d,e)=>{d/=2;Hg.length=d;b=e>>3;for(c=0;c<d;c++)Hg[c]=E[b+2*c]?E[b+2*
c+1]:Qa[b+2*c+1];return(0,Ig[a])(...Hg)};function lc(){if(w)return L(17,1);ce=!1;$d=0}
var mc=a=>{w?postMessage({cmd:"cleanupThread",thread:a}):ke(Yd[a])},nc=a=>{u&&Yd[a].ref()},oc=()=>{throw new hb;},Jg=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(D[b>>2]=fg(d));return a},pc=(a,b,c)=>{a=X(a);b=xg(b,"emval::as");return Jg(b,c,a)},Kg=[],qc=(a,b,c,d)=>{a=Kg[a];b=X(b);return a(null,b,c,d)},Lg={},Mg=a=>{var b=Lg[a];return void 0===b?R(a):b},Ng=()=>"object"==typeof globalThis?globalThis:Function("return this")(),sc=a=>{if(0===a)return fg(Ng());a=Mg(a);return fg(Ng()[a])},Og=a=>{var b=
Kg.length;Kg.push(a);return b},Pg=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=xg(D[b+4*d>>2],"parameter "+d);return c},tc=(a,b,c)=>{b=Pg(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,g=[];0===c&&g.push("obj");for(var h=["retType"],k=[d],m=0;m<a;++m)g.push("arg"+m),h.push("argType"+m),k.push(b[m]),e+=`  var arg${m} = argType${m}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=b[m].argPackAdvance;e+=`  var rv = ${1===c?"new func":"func.call"}(${g.join(", ")});\n`;
d.ye||(h.push("emval_returnValue"),k.push(Jg),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");h.push(e+"};\n");a=og(h)(...k);c=`methodCaller<(${b.map(p=>p.name).join(", ")}) => ${d.name}>`;return Og(Yf(c,a))},uc=a=>{a=Mg(a);return fg(n[a])},vc=(a,b)=>{a=X(a);b=X(b);return fg(a[b])},wc=a=>{9<a&&(ug[a+1]+=1)},xc=(a,b)=>{a=X(a);b=X(b);return a instanceof b},yc=a=>{a=X(a);return"number"==typeof a},zc=a=>{a=X(a);return"string"==typeof a},Ac=a=>fg(Mg(a)),Bc=a=>{var b=X(a);vf(b);rc(a)},
Cc=(a,b,c)=>{a=X(a);b=X(b);c=X(c);a[b]=c},Dc=(a,b)=>{a=xg(a,"_emval_take_value");a=a.readValueFromPointer(b);return fg(a)},Ec=a=>{a=X(a);return fg(typeof a)};function Fc(a,b){a=ae(a);a=new Date(1E3*a);C[b>>2]=a.getUTCSeconds();C[b+4>>2]=a.getUTCMinutes();C[b+8>>2]=a.getUTCHours();C[b+12>>2]=a.getUTCDate();C[b+16>>2]=a.getUTCMonth();C[b+20>>2]=a.getUTCFullYear()-1900;C[b+24>>2]=a.getUTCDay();C[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0}
var Qg=a=>0===a%4&&(0!==a%100||0===a%400),Rg=[0,31,60,91,121,152,182,213,244,274,305,335],Sg=[0,31,59,90,120,151,181,212,243,273,304,334];
function Gc(a,b){a=ae(a);a=new Date(1E3*a);C[b>>2]=a.getSeconds();C[b+4>>2]=a.getMinutes();C[b+8>>2]=a.getHours();C[b+12>>2]=a.getDate();C[b+16>>2]=a.getMonth();C[b+20>>2]=a.getFullYear()-1900;C[b+24>>2]=a.getDay();C[b+28>>2]=(Qg(a.getFullYear())?Rg:Sg)[a.getMonth()]+a.getDate()-1|0;C[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();C[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}
function Hc(a,b,c,d,e,f,g){if(w)return L(18,1,a,b,c,d,e,f,g);e=ae(e);try{if(isNaN(e))return 61;var h=Q(d),k=FS.Pc(h,a,e,b,c),m=k.yc;C[f>>2]=k.od;D[g>>2]=m;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return-p.Bc}}
function Ic(a,b,c,d,e,f){if(w)return L(19,1,a,b,c,d,e,f);f=ae(f);try{var g=Q(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.uc(43);if(!(d&2)){var h=A.slice(a,a+b);FS.Vc(g,h,c,b,d)}}}catch(k){if("undefined"==typeof FS||"ErrnoError"!==k.name)throw k;return-k.Bc}}
var Jc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var h=g.getTimezoneOffset();D[a>>2]=60*Math.max(e,h);C[b>>2]=Number(e!=h);a=k=>k.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];f=a(f);g=a(g);h<e?(Ge(f,A,c,17),Ge(g,A,d,17)):(Ge(f,A,d,17),Ge(g,A,c,17))},Kc=()=>{},Lc=a=>{console.error(M(a))},Mc=()=>Date.now(),Nc=()=>{$d+=1;throw"unwind";},Oc=()=>A.length,Pc;Pc=()=>performance.timeOrigin+performance.now();
var Qc=()=>u?require("os").cpus().length:navigator.hardwareConcurrency,Rc=()=>!1,Tg={},Vg=()=>{if(!Ug){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ia||"./this.program"},b;for(b in Tg)void 0===Tg[b]?delete a[b]:a[b]=Tg[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ug=c}return Ug},Ug;
function Sc(a,b){if(w)return L(20,1,a,b);var c=0;Vg().forEach((d,e)=>{var f=b+c;e=D[a+4*e>>2]=f;for(f=0;f<d.length;++f)z[e++]=d.charCodeAt(f);z[e]=0;c+=d.length+1});return 0}function Tc(a,b){if(w)return L(21,1,a,b);var c=Vg();D[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);D[b>>2]=d;return 0}function Vc(a){if(w)return L(22,1,a);try{var b=Q(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.Bc}}
function Wc(a,b){if(w)return L(23,1,a,b);try{var c=Q(a),d=c.tty?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;z[b]=d;Na[b+2>>1]=0;E[b+8>>3]=BigInt(0);E[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.Bc}}
function Xc(a,b,c,d){if(w)return L(24,1,a,b,c,d);try{a:{var e=Q(a);a=b;for(var f,g=b=0;g<c;g++){var h=D[a>>2],k=D[a+4>>2];a+=8;var m=FS.read(e,z,h,k,f);if(0>m){var p=-1;break a}b+=m;if(m<k)break;"undefined"!=typeof f&&(f+=m)}p=b}D[d>>2]=p;return 0}catch(q){if("undefined"==typeof FS||"ErrnoError"!==q.name)throw q;return q.Bc}}
function Yc(a,b,c,d){if(w)return L(25,1,a,b,c,d);b=ae(b);try{if(isNaN(b))return 61;var e=Q(a);FS.llseek(e,b,c);E[d>>3]=BigInt(e.position);e.yd&&0===b&&0===c&&(e.yd=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.Bc}}
function Zc(a,b,c,d){if(w)return L(26,1,a,b,c,d);try{a:{var e=Q(a);a=b;for(var f,g=b=0;g<c;g++){var h=D[a>>2],k=D[a+4>>2];a+=8;var m=FS.write(e,z,h,k,f);if(0>m){var p=-1;break a}b+=m;"undefined"!=typeof f&&(f+=m)}p=b}D[d>>2]=p;return 0}catch(q){if("undefined"==typeof FS||"ErrnoError"!==q.name)throw q;return q.Bc}}
var ad=(a,b)=>{Ae(A.subarray(a,a+b));return 0},Wg=[31,29,31,30,31,30,31,31,30,31,30,31],Xg=[31,28,31,30,31,30,31,31,30,31,30,31],Qd=(a,b,c,d)=>{function e(l,t,v){for(l="number"==typeof l?l.toString():l||"";l.length<t;)l=v[0]+l;return l}function f(l,t){return e(l,t,"0")}function g(l,t){function v(O){return 0>O?-1:0<O?1:0}var G;0===(G=v(l.getFullYear()-t.getFullYear()))&&0===(G=v(l.getMonth()-t.getMonth()))&&(G=v(l.getDate()-t.getDate()));return G}function h(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-
1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function k(l){var t=l.bd;for(l=new Date((new Date(l.cd+1900,0,1)).getTime());0<t;){var v=l.getMonth(),G=(Qg(l.getFullYear())?Wg:Xg)[v];if(t>G-l.getDate())t-=G-l.getDate()+1,l.setDate(1),11>v?l.setMonth(v+1):(l.setMonth(0),l.setFullYear(l.getFullYear()+
1));else{l.setDate(l.getDate()+t);break}}v=new Date(l.getFullYear()+1,0,4);t=h(new Date(l.getFullYear(),0,4));v=h(v);return 0>=g(t,l)?0>=g(v,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var m=D[d+40>>2];d={Oe:C[d>>2],Ne:C[d+4>>2],ud:C[d+8>>2],Jd:C[d+12>>2],vd:C[d+16>>2],cd:C[d+20>>2],Tc:C[d+24>>2],bd:C[d+28>>2],hf:C[d+32>>2],Me:C[d+36>>2],Pe:m?M(m):""};c=M(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y",
"%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in m)c=c.replace(new RegExp(p,"g"),m[p]);var q="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),r="January February March April May June July August September October November December".split(" ");m={"%a":l=>q[l.Tc].substring(0,3),"%A":l=>
q[l.Tc],"%b":l=>r[l.vd].substring(0,3),"%B":l=>r[l.vd],"%C":l=>f((l.cd+1900)/100|0,2),"%d":l=>f(l.Jd,2),"%e":l=>e(l.Jd,2," "),"%g":l=>k(l).toString().substring(2),"%G":k,"%H":l=>f(l.ud,2),"%I":l=>{l=l.ud;0==l?l=12:12<l&&(l-=12);return f(l,2)},"%j":l=>{for(var t=0,v=0;v<=l.vd-1;t+=(Qg(l.cd+1900)?Wg:Xg)[v++]);return f(l.Jd+t,3)},"%m":l=>f(l.vd+1,2),"%M":l=>f(l.Ne,2),"%n":()=>"\n","%p":l=>0<=l.ud&&12>l.ud?"AM":"PM","%S":l=>f(l.Oe,2),"%t":()=>"\t","%u":l=>l.Tc||7,"%U":l=>f(Math.floor((l.bd+7-l.Tc)/7),
2),"%V":l=>{var t=Math.floor((l.bd+7-(l.Tc+6)%7)/7);2>=(l.Tc+371-l.bd-2)%7&&t++;if(t)53==t&&(v=(l.Tc+371-l.bd)%7,4==v||3==v&&Qg(l.cd)||(t=1));else{t=52;var v=(l.Tc+7-l.bd-1)%7;(4==v||5==v&&Qg(l.cd%400-1))&&t++}return f(t,2)},"%w":l=>l.Tc,"%W":l=>f(Math.floor((l.bd+7-(l.Tc+6)%7)/7),2),"%y":l=>(l.cd+1900).toString().substring(2),"%Y":l=>l.cd+1900,"%z":l=>{l=l.Me;var t=0<=l;l=Math.abs(l)/60;return(t?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":l=>l.Pe,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");
for(p in m)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),m[p](d)));c=c.replace(/\0\0/g,"%");p=He(c,!1);if(p.length>b)return 0;z.set(p,a);return p.length-1},Yg=[],Zg;n.incrementExceptionRefcount=a=>qe(a);n.decrementExceptionRefcount=a=>$g(a);var jb=a=>{var b=H(),c=Sd(4),d=Sd(4);ah(a,c,d);a=D[c>>2];d=D[d>>2];c=M(a);U(a);if(d){var e=M(d);U(d)}I(b);return[c,e]};n.getExceptionMessage=a=>jb(a);w?ce=!1:Sa.unshift(()=>{db();eb()});
FS.createPreloadedFile=(a,b,c,d,e,f,g,h,k,m)=>{function p(r){function l(t){m?.();h||FS.createDataFile(a,b,t,d,e,k);f?.();eb()}Te(r,q,l,()=>{g?.();eb()})||l(r)}var q=b?Be(ye(a,b)):a;db();"string"==typeof c?Re(c,p,g):p(c)};FS.Id();u&&NODEFS.Id();if(!u)throw Error("NODERAWFS is currently only supported on Node.js environment.");var $e=Object.assign({},FS);FS.init=af.init;Af=n.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
for(var bh=Array(256),ch=0;256>ch;++ch)bh[ch]=String.fromCharCode(ch);Ef=bh;S=n.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(Xf.prototype,{isAliasOf:function(a){if(!(this instanceof Xf&&a instanceof Xf))return!1;var b=this.vc.Dc.Ac,c=this.vc.yc;a.vc=a.vc;var d=a.vc.Dc.Ac;for(a=a.vc.yc;b.Ic;)c=b.md(c),b=b.Ic;for(;d.Ic;)a=d.md(a),d=d.Ic;return b===d&&c===a},clone:function(){this.vc.yc||Kf(this);if(this.vc.ld)return this.vc.count.value+=1,this;var a=Vf,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.vc;a=a(c.call(b,d,{vc:{value:{count:e.count,gd:e.gd,ld:e.ld,yc:e.yc,Dc:e.Dc,Gc:e.Gc,Kc:e.Kc}}}));a.vc.count.value+=
1;a.vc.gd=!1;return a},["delete"](){this.vc.yc||Kf(this);if(this.vc.gd&&!this.vc.ld)throw new S("Object already scheduled for deletion");Nf(this);var a=this.vc;--a.count.value;0===a.count.value&&(a.Gc?a.Kc.Sc(a.Gc):a.Dc.Ac.Sc(a.yc));this.vc.ld||(this.vc.Gc=void 0,this.vc.yc=void 0)},isDeleted:function(){return!this.vc.yc},deleteLater:function(){this.vc.yc||Kf(this);if(this.vc.gd&&!this.vc.ld)throw new S("Object already scheduled for deletion");Qf.push(this);1===Qf.length&&Sf&&Sf(Rf);this.vc.gd=!0;
return this}});n.getInheritedInstanceCount=()=>Object.keys(Tf).length;n.getLiveInheritedInstances=()=>{var a=[],b;for(b in Tf)Tf.hasOwnProperty(b)&&a.push(Tf[b]);return a};n.setAutoDeleteLater=a=>{Lf=a};n.flushPendingDeletes=Rf;n.setDelayFunction=a=>{Sf=a;Qf.length&&Sf&&Sf(Rf)};
Object.assign(hg.prototype,{pe(a){this.Xd&&(a=this.Xd(a));return a},Od(a){this.Sc?.(a)},argPackAdvance:Df,readValueFromPointer:wf,fromWireType:function(a){function b(){return this.sd?Wf(this.Ac.Xc,{Dc:this.De,yc:c,Kc:this,Gc:a}):Wf(this.Ac.Xc,{Dc:this,yc:a})}var c=this.pe(a);if(!c)return this.Od(a),null;var d=Uf(this.Ac,c);if(void 0!==d){if(0===d.vc.count.value)return d.vc.yc=c,d.vc.Gc=a,d.clone();d=d.clone();this.Od(a);return d}d=this.Ac.ne(c);d=Pf[d];if(!d)return b.call(this);d=this.qd?d.he:d.pointerType;
var e=Of(c,this.Ac,d.Ac);return null===e?b.call(this):this.sd?Wf(d.Ac.Xc,{Dc:d,yc:e,Kc:this,Gc:a}):Wf(d.Ac.Xc,{Dc:d,yc:e})}});jg=n.UnboundTypeError=((a,b)=>{var c=Yf(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
ug.push(0,1,void 0,1,null,1,!0,1,!1,1);n.count_emval_handles=()=>ug.length/2-5-tg.length;
var Ig=[Pd,fe,we,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,lc,Hc,Ic,Sc,Tc,Vc,Wc,Xc,Yc,Zc],pb,Y=function(){function a(c,d){Y=c.exports;ie.push(Y.Nb);J=Y.Fb;Ta.unshift(Y.Ab);Ka=d;eb();return Y}var b=xa();db();if(n.instantiateWasm)try{return n.instantiateWasm(b,a)}catch(c){y(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}kb||=gb("vips.wasm")?"vips.wasm":n.locateFile?n.locateFile("vips.wasm",la):la+"vips.wasm";ob(b,function(c){a(c.instance,c.module)}).catch(ba);return{}}(),
kg=a=>(kg=Y.Bb)(a),Ea=()=>(Ea=Y.Cb)();n.__ZdlPv=a=>(n.__ZdlPv=Y.Db)(a);var wa=()=>(wa=Y.Eb)(),Hf=a=>(Hf=Y.Gb)(a),dh=n._main=(a,b)=>(dh=n._main=Y.Hb)(a,b),U=a=>(U=Y.Ib)(a),he=a=>(he=Y.Jb)(a);n._realloc=(a,b)=>(n._realloc=Y.Kb)(a,b);n._calloc=(a,b)=>(n._calloc=Y.Lb)(a,b);n._emscripten_builtin_free=a=>(n._emscripten_builtin_free=Y.Mb)(a);var Ne=(a,b)=>(Ne=Y.Ob)(a,b);n._emscripten_builtin_malloc=a=>(n._emscripten_builtin_malloc=Y.Pb)(a);var ge=()=>(ge=Y.Qb)();
n.___libc_calloc=(a,b)=>(n.___libc_calloc=Y.Rb)(a,b);n.___libc_free=a=>(n.___libc_free=Y.Sb)(a);n.___libc_malloc=a=>(n.___libc_malloc=Y.Tb)(a);var Aa=(a,b,c,d,e,f)=>(Aa=Y.Ub)(a,b,c,d,e,f),Ia=()=>(Ia=Y.Vb)(),be=(a,b,c,d,e)=>(be=Y.Wb)(a,b,c,d,e),je=a=>(je=Y.Xb)(a),Ga=a=>(Ga=Y.Yb)(a),Gg=()=>(Gg=Y.Zb)();n.__ZdaPv=a=>(n.__ZdaPv=Y._b)(a);n.__ZdaPvm=(a,b)=>(n.__ZdaPvm=Y.$b)(a,b);n.__ZdlPvm=(a,b)=>(n.__ZdlPvm=Y.ac)(a,b);n.__Znaj=a=>(n.__Znaj=Y.bc)(a);
n.__ZnajSt11align_val_t=(a,b)=>(n.__ZnajSt11align_val_t=Y.cc)(a,b);n.__Znwj=a=>(n.__Znwj=Y.dc)(a);n.__ZnwjSt11align_val_t=(a,b)=>(n.__ZnwjSt11align_val_t=Y.ec)(a,b);n.___libc_realloc=(a,b)=>(n.___libc_realloc=Y.fc)(a,b);n._malloc_size=a=>(n._malloc_size=Y.gc)(a);n._malloc_usable_size=a=>(n._malloc_usable_size=Y.hc)(a);n._reallocf=(a,b)=>(n._reallocf=Y.ic)(a,b);
var Z=(a,b)=>(Z=Y.jc)(a,b),te=a=>(te=Y.kc)(a),le=(a,b)=>(le=Y.lc)(a,b),I=a=>(I=Y.mc)(a),Sd=a=>(Sd=Y.nc)(a),H=()=>(H=Y.oc)(),qe=a=>(qe=Y.pc)(a),$g=a=>($g=Y.qc)(a),ah=(a,b,c)=>(ah=Y.rc)(a,b,c),ue=(a,b,c)=>(ue=Y.sc)(a,b,c),re=a=>(re=Y.tc)(a);function rd(a,b){var c=H();try{J.get(a)(b)}catch(d){I(c);if(!(d instanceof F))throw d;Z(1,0)}}function yd(a,b,c,d){var e=H();try{J.get(a)(b,c,d)}catch(f){I(e);if(!(f instanceof F))throw f;Z(1,0)}}
function gd(a,b,c){var d=H();try{return J.get(a)(b,c)}catch(e){I(d);if(!(e instanceof F))throw e;Z(1,0)}}function fd(a,b){var c=H();try{return J.get(a)(b)}catch(d){I(c);if(!(d instanceof F))throw d;Z(1,0)}}function ed(a){var b=H();try{return J.get(a)()}catch(c){I(b);if(!(c instanceof F))throw c;Z(1,0)}}function qd(a){var b=H();try{J.get(a)()}catch(c){I(b);if(!(c instanceof F))throw c;Z(1,0)}}
function Fd(a,b,c,d,e){var f=H();try{J.get(a)(b,c,d,e)}catch(g){I(f);if(!(g instanceof F))throw g;Z(1,0)}}function cd(a,b,c,d){var e=H();try{return J.get(a)(b,c,d)}catch(f){I(e);if(!(f instanceof F))throw f;Z(1,0)}}function jd(a,b,c,d){var e=H();try{return J.get(a)(b,c,d)}catch(f){I(e);if(!(f instanceof F))throw f;Z(1,0)}}function td(a,b,c){var d=H();try{J.get(a)(b,c)}catch(e){I(d);if(!(e instanceof F))throw e;Z(1,0)}}
function ld(a,b,c,d,e,f){var g=H();try{return J.get(a)(b,c,d,e,f)}catch(h){I(g);if(!(h instanceof F))throw h;Z(1,0)}}function Gd(a,b,c,d,e,f){var g=H();try{J.get(a)(b,c,d,e,f)}catch(h){I(g);if(!(h instanceof F))throw h;Z(1,0)}}function md(a,b,c,d,e,f,g){var h=H();try{return J.get(a)(b,c,d,e,f,g)}catch(k){I(h);if(!(k instanceof F))throw k;Z(1,0)}}function kd(a,b,c,d,e){var f=H();try{return J.get(a)(b,c,d,e)}catch(g){I(f);if(!(g instanceof F))throw g;Z(1,0)}}
function ud(a,b,c,d){var e=H();try{J.get(a)(b,c,d)}catch(f){I(e);if(!(f instanceof F))throw f;Z(1,0)}}function vd(a,b,c,d,e){var f=H();try{J.get(a)(b,c,d,e)}catch(g){I(f);if(!(g instanceof F))throw g;Z(1,0)}}function hd(a,b,c,d){var e=H();try{return J.get(a)(b,c,d)}catch(f){I(e);if(!(f instanceof F))throw f;Z(1,0)}}function dd(a,b,c,d,e){var f=H();try{return J.get(a)(b,c,d,e)}catch(g){I(f);if(!(g instanceof F))throw g;Z(1,0)}}
function Ld(a,b,c,d,e,f,g,h,k,m,p){var q=H();try{J.get(a)(b,c,d,e,f,g,h,k,m,p)}catch(r){I(q);if(!(r instanceof F))throw r;Z(1,0)}}function Hd(a,b,c,d,e,f,g){var h=H();try{J.get(a)(b,c,d,e,f,g)}catch(k){I(h);if(!(k instanceof F))throw k;Z(1,0)}}function Id(a,b,c,d,e,f,g,h){var k=H();try{J.get(a)(b,c,d,e,f,g,h)}catch(m){I(k);if(!(m instanceof F))throw m;Z(1,0)}}function bd(a,b,c){var d=H();try{return J.get(a)(b,c)}catch(e){I(d);if(!(e instanceof F))throw e;Z(1,0)}}
function xd(a,b,c,d,e){var f=H();try{J.get(a)(b,c,d,e)}catch(g){I(f);if(!(g instanceof F))throw g;Z(1,0)}}function zd(a,b,c,d,e){var f=H();try{J.get(a)(b,c,d,e)}catch(g){I(f);if(!(g instanceof F))throw g;Z(1,0)}}function sd(a,b,c,d,e){var f=H();try{J.get(a)(b,c,d,e)}catch(g){I(f);if(!(g instanceof F))throw g;Z(1,0)}}function Cd(a,b,c,d,e,f,g,h){var k=H();try{J.get(a)(b,c,d,e,f,g,h)}catch(m){I(k);if(!(m instanceof F))throw m;Z(1,0)}}
function Ad(a,b,c,d,e,f,g,h,k,m){var p=H();try{J.get(a)(b,c,d,e,f,g,h,k,m)}catch(q){I(p);if(!(q instanceof F))throw q;Z(1,0)}}function Bd(a,b,c,d,e,f,g,h,k){var m=H();try{J.get(a)(b,c,d,e,f,g,h,k)}catch(p){I(m);if(!(p instanceof F))throw p;Z(1,0)}}function Ed(a,b,c,d,e,f){var g=H();try{J.get(a)(b,c,d,e,f)}catch(h){I(g);if(!(h instanceof F))throw h;Z(1,0)}}function Dd(a,b,c,d,e,f,g){var h=H();try{J.get(a)(b,c,d,e,f,g)}catch(k){I(h);if(!(k instanceof F))throw k;Z(1,0)}}
function Nd(a,b,c,d,e,f,g,h,k,m,p,q,r){var l=H();try{J.get(a)(b,c,d,e,f,g,h,k,m,p,q,r)}catch(t){I(l);if(!(t instanceof F))throw t;Z(1,0)}}function Md(a,b,c,d,e,f,g,h,k,m,p,q){var r=H();try{J.get(a)(b,c,d,e,f,g,h,k,m,p,q)}catch(l){I(r);if(!(l instanceof F))throw l;Z(1,0)}}function Kd(a,b,c,d,e,f,g,h,k,m){var p=H();try{J.get(a)(b,c,d,e,f,g,h,k,m)}catch(q){I(p);if(!(q instanceof F))throw q;Z(1,0)}}
function Jd(a,b,c,d,e,f,g,h,k){var m=H();try{J.get(a)(b,c,d,e,f,g,h,k)}catch(p){I(m);if(!(p instanceof F))throw p;Z(1,0)}}function Od(a,b,c,d,e,f,g,h,k,m,p,q,r,l){var t=H();try{J.get(a)(b,c,d,e,f,g,h,k,m,p,q,r,l)}catch(v){I(t);if(!(v instanceof F))throw v;Z(1,0)}}function wd(a,b,c,d,e,f){var g=H();try{J.get(a)(b,c,d,e,f)}catch(h){I(g);if(!(h instanceof F))throw h;Z(1,0)}}function nd(a,b,c,d,e,f,g,h){var k=H();try{return J.get(a)(b,c,d,e,f,g,h)}catch(m){I(k);if(!(m instanceof F))throw m;Z(1,0)}}
function pd(a,b){var c=H();try{return J.get(a)(b)}catch(d){I(c);if(!(d instanceof F))throw d;Z(1,0);return 0n}}function od(a,b,c,d,e,f,g,h,k,m,p,q,r){var l=H();try{return J.get(a)(b,c,d,e,f,g,h,k,m,p,q,r)}catch(t){I(l);if(!(t instanceof F))throw t;Z(1,0)}}n.bigintToI53Checked=ae;n.ENV=Tg;
n.addFunction=(a,b)=>{if(!Zg){Zg=new WeakMap;var c=J.length;if(Zg)for(var d=0;d<0+c;d++){var e=J.get(d);e&&Zg.set(e,d)}}if(c=Zg.get(a)||0)return c;if(Yg.length)c=Yg.pop();else{try{J.grow(1)}catch(h){if(!(h instanceof RangeError))throw h;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=J.length-1}try{J.set(c,a)}catch(h){if(!(h instanceof TypeError))throw h;if("function"==typeof WebAssembly.Function){d=WebAssembly.Function;e={i:"i32",j:"i64",f:"f32",d:"f64",e:"externref",p:"i32"};for(var f=
{parameters:[],results:"v"==b[0]?[]:[e[b[0]]]},g=1;g<b.length;++g)f.parameters.push(e[b[g]]);b=new d(f,a)}else{d=[1];e=b.slice(0,1);b=b.slice(1);f={i:127,p:127,j:126,f:125,d:124,e:111};d.push(96);g=b.length;128>g?d.push(g):d.push(g%128|128,g>>7);for(g=0;g<b.length;++g)d.push(f[b[g]]);"v"==e?d.push(0):d.push(1,f[e]);b=[0,97,115,109,1,0,0,0,1];e=d.length;128>e?b.push(e):b.push(e%128|128,e>>7);b.push(...d);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));b=(new WebAssembly.Instance(b,
{e:{f:a}})).exports.f}J.set(c,b)}Zg.set(a,c);return c};n.deletionQueue=Qf;var eh;cb=function fh(){eh||gh();eh||(cb=fh)};
function gh(){function a(){if(!eh&&(eh=!0,n.calledRun=!0,!La)){Za();w||$a(Ua);aa(n);if(n.onRuntimeInitialized)n.onRuntimeInitialized();if(hh){var b=dh;try{var c=b(0,0);Uc(c,!0)}catch(d){ee(d)}}if(!w){if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;)b=n.postRun.shift(),Wa.unshift(b);$a(Wa)}}}if(!(0<ab))if(w)aa(n),Za(),startWorker(n);else{if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)Sa.unshift(n.preRun.shift());$a(Sa);0<
ab||(n.setStatus?(n.setStatus("Running..."),setTimeout(function(){setTimeout(function(){n.setStatus("")},1);a()},1)):a())}}if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.pop()();var hh=!0;n.noInitialRun&&(hh=!1);gh();moduleRtn=ca;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Vips;
else if (typeof define === 'function' && define['amd'])
  define([], () => Vips);
var isPthread = globalThis.self?.name === 'em-pthread';
var isNode = typeof globalThis.process?.versions?.node == 'string';
if (isNode) isPthread = require('worker_threads').workerData === 'em-pthread'

// When running as a pthread, construct a new instance on startup
isPthread && Vips();
